In [1]:
# Libraries

import sys
from bs4 import BeautifulSoup
import Cleaning as cln
from collections import defaultdict, Counter
import dask
import dask.dataframe as dd
from dask.diagnostics import ProgressBar
from dask.multiprocessing import get
from bokeh.io import export_png
from bokeh.models import ColumnDataSource, TableColumn, DataTable
import datetime
import Exploration as exp
from gensim.models import TfidfModel, ldamodel, LdaMulticore, CoherenceModel
from gensim.corpora import Dictionary
import gmaps
from importlib import reload
from itertools import product
reload(cln)
reload(exp)
from langdetect import detect, DetectorFactory
from IPython.display import display
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import multiprocessing
import nltk
import numpy as np
import os
import pandas as pd
import pyLDAvis
import pickle
import random
import re
import scipy
import seaborn as sns
import sklearn as skl
from sklearn import manifold, metrics, model_selection, preprocessing, decomposition
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from scipy.cluster.hierarchy import dendrogram
from sklearn.datasets import make_classification
from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_selection import SelectFromModel
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV, train_test_split, cross_val_score, KFold
from sklearn.multiclass import OneVsRestClassifier, OneVsOneClassifier
from sklearn.preprocessing import label_binarize, LabelEncoder, OneHotEncoder, RobustScaler
from sklearn.svm import SVC
from spellchecker import SpellChecker
import statistics
import string
import time
import Transformer as mytransformer
reload(mytransformer)

pd.set_option('display.max_colwidth', 40)
pd.set_option('display.max_columns', 186)

%matplotlib widget
# %matplotlib inline

D:\Anaconda3\lib\site-packages\gensim\similarities\__init__.py:15: UserWarning: The gensim.similarities.levenshtein submodule is disabled, because the optional Levenshtein package <https://pypi.org/project/python-Levenshtein/> is unavailable. Install Levenhstein (e.g. `pip install python-Levenshtein`) to suppress this warning.
  warnings.warn(msg)


In [2]:
class progress_bar():
    
    def __init__(self, barLength = None, title = None, progress_lim = None, time_lim=None):
        self.first_time = datetime.datetime.now()
        if barLength is not None:
            self.barLength = 40
        else :
            self.barLength = barLength
        
        if title is None:
            self.title = ''
        else:
            self.title = title
            
        if progress_lim is not None:
            self.progress_lim = progress_lim
            self.step_progress = 1/self.progress_lim
            
            self.time_lim = datetime.timedelta(hours=10)
            self.step_time = 1
            
            self.lim_kind = 'progress'
        elif time_lim is not None:
            self.progress_lim = 0
            self.step_progress = 1
            
            self.time_lim = datetime.timedelta(seconds = time_lim)
            self.step_time = 1/time_lim
            
            self.lim_kind = 'time'
        else:
            self.progress_lim = 0.01
            self.time_lim = datetime.timedelta(hours=10)
            self.time_lim = 1
            self.lim_kind = 'progress'
            
        self.old_progress = 0
        self.old_timer = datetime.timedelta(seconds = 0)
        self.progress = 0
        self.timer = datetime.timedelta(seconds = 0)
        
    def set_progress(self, progress):
        self.old_progress = -1
        self.update_progress(progress)
        
    def reset(self, title=None, progress=None):
        self.first_time = datetime.datetime.now()
        self.old_progress = -1
        self.old_timer = datetime.timedelta(seconds = 0)
        if title is not None:
            self.title = title
        if progress is None:
            self.update_progress(0)
        else:
            self.update_progress(progress)
            
    def update_progress(self, progress):
        self.timer = datetime.datetime.now() - self.first_time
#         status = datetime.datetime.strptime(str(time_spent), "%H:%M:%S")
        status = str(self.timer).format("%H:%M:%.0S")
        if isinstance(progress, int):
            progress = float(progress)
        if not isinstance(progress, float):
            progress = 0
            status = "error: progress var must be float\r\n"
        if progress < 0:
            progress = 0
            status = "Halt...\r\n"
        if progress >= 1 and self.old_progress < 1:
            self.old_progress = progress
            progress = 1
            status = "Done (" + status + ")\r\n"
        
        block = int(round(self.barLength*progress))
        if ((self.lim_kind == 'progress') & (progress >= self.old_progress + self.progress_lim)) |\
            ((self.lim_kind == 'time') & (self.timer >= self.old_timer + self.time_lim)):
            
            self.old_progress = (progress*self.step_progress - (progress*self.step_progress % 1))/self.step_progress
            self.old_timer = datetime.timedelta(
                seconds = 
                ( 
                    self.timer.total_seconds()*self.step_time
                    - (self.timer.total_seconds()*self.step_time % 1)
                )
                /self.step_time
            )
            
            text = "\rProgress {0}: [{1}] {2:.2f}% {3:s}".format( self.title, "#"*block + "-"*(self.barLength-block), progress*100, status)
            sys.stdout.write(text)
            sys.stdout.flush()
            
def save_df_as_image(df, path, width=None, height=None, width_policy = None, height_policy = None, b_index=False):
    df_copy = df.copy()
    if b_index:
        df_copy.insert(0, '', df_copy.index.values)
    
    if width is None:
        width = 280
    if height is None:
        height = 280
    if height_policy is None:
        height_policy = "auto"
    if width_policy is None:
        width_policy = "auto"
        
    source = ColumnDataSource(df_copy)
    df_columns = df_copy.columns.values

    columns_for_table = []
    
    for column in df_columns:
        columns_for_table.append(TableColumn(field=column, title=column))

    data_table = DataTable(source = source,
                           columns = columns_for_table,
                           width = width,
                           height = height,
                           height_policy = height_policy,
                           width_policy = width_policy,
                           index_position = None)
    export_png(data_table, filename = path)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


## 1) Mise en forme du jeu de donné

Requet SQL :
``` mysql
SELECT Id, PostTypeId, ParentId, CreationDate, Score, ViewCount, Body, OwnerUserId, Title, Tags, AnswerCount, CommentCount, FavoriteCount, ClosedDate
        FROM posts
        WHERE ViewCount > 50
        AND (CreationDate BETWEEN '2020-01-01' AND '2020-01-31') AND AnswerCount > 0 AND CommentCount > 5 AND len(Tags) > 0
        ORDER BY CreationDate
```

Equilibré le nombre de post sur chaque mois et sur chaque année. 

In [3]:
# USING CSV file for data
# Method from : http://www.xavierdupre.fr/app/ensae_teaching_cs/helpsphinx/notebooks/prepare_data_2017.html

FILE_2019 = "./Data/Posts_2019.csv"
data_2019 = pd.read_csv(FILE_2019, encoding="utf-8", low_memory=False, error_bad_lines=False)
print(FILE_2019, ' : ', os.stat(FILE_2019).st_size / 2**20, 'Mo, ', data_2019.shape)

FILE_2020 = "./Data/Posts_2020.csv"
data_2020 = pd.read_csv(FILE_2020, encoding="utf-8", low_memory=False, error_bad_lines=False)
print(FILE_2020, ' : ', os.stat(FILE_2020).st_size / 2**20, 'Mo', data_2020.shape)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


./Data/Posts_2019.csv  :  83.79751873016357 Mo,  (42393, 14)
./Data/Posts_2020.csv  :  37.11684703826904 Mo (17090, 14)


In [4]:
DataRaw = pd.concat([data_2019, data_2020], axis = 0, ignore_index=True)
DataRaw['CreationDate'] = DataRaw['CreationDate'].astype("datetime64")
DataRaw['ClosedDate'] = DataRaw['ClosedDate'].astype("datetime64")
DataRaw.describe(include = 'all', datetime_is_numeric=True)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Id  PostTypeId  ParentId                   CreationDate  \
count   5.948300e+04     59483.0       0.0                          59483   
unique           NaN         NaN       NaN                            NaN   
top              NaN         NaN       NaN                            NaN   
freq             NaN         NaN       NaN                            NaN   
mean    5.798659e+07         1.0       NaN  2019-09-14 07:00:44.380444928   
min     5.399238e+07         1.0       NaN            2019-01-01 00:48:55   
25%     5.548793e+07         1.0       NaN     2019-04-03 05:52:03.500000   
50%     5.742721e+07         1.0       NaN            2019-08-09 09:31:42   
75%     5.996404e+07         1.0       NaN     2020-01-29 09:27:59.500000   
max     6.552585e+07         1.0       NaN            2020-12-31 22:00:47   
std     2.932752e+06         0.0       NaN                            NaN   

               Score     ViewCount                                     Body  \
count   59483.000000  5.948300e+04                                    59483   
unique           NaN           NaN                                    59483   
top              NaN           NaN  <p>I am trying to figure out how to ...   
freq             NaN           NaN                                        1   
mean        9.164165  1.217933e+04                                      NaN   
min       -13.000000  5.001000e+03                                      NaN   
25%         2.000000  6.081000e+03                                      NaN   
50%         5.000000  7.899000e+03                                      NaN   
75%        10.000000  1.211200e+04                                      NaN   
max       716.000000  1.579886e+06                                      NaN   
std        19.124309  1.769234e+04                                      NaN   

         OwnerUserId                             Title             Tags  \
count   5.848000e+04                             59483            59483   
unique           NaN                             59483            41177   
top              NaN  Hidden size vs input size in RNN  <flutter><dart>   
freq             NaN                                 1              392   
mean    7.208163e+06                               NaN              NaN   
min     9.100000e+01                               NaN              NaN   
25%     3.497671e+06                               NaN              NaN   
50%     7.726327e+06                               NaN              NaN   
75%     1.091122e+07                               NaN              NaN   
max     1.571046e+07                               NaN              NaN   
std     4.095239e+06                               NaN              NaN   

         AnswerCount  CommentCount  FavoriteCount  \
count   59483.000000  59483.000000   35825.000000   
unique           NaN           NaN            NaN   
top              NaN           NaN            NaN   
freq             NaN           NaN            NaN   
mean        2.737606      2.017736       3.079749   
min         1.000000      0.000000       0.000000   
25%         1.000000      0.000000       1.000000   
50%         2.000000      1.000000       2.000000   
75%         3.000000      3.000000       3.000000   
max        51.000000     50.000000     203.000000   
std         2.354607      2.744228       5.467424   

                           ClosedDate  
count                            1995  
unique                            NaN  
top                               NaN  
freq                              NaN  
mean    2019-12-29 06:25:43.028070144  
min               2019-01-01 10:07:16  
25%        2019-04-30 06:37:09.500000  
50%               2019-11-08 14:20:51  
75%               2020-07-27 01:43:07  
max               2021-12-03 04:33:51  
std                               NaN

In [5]:
# USING CSV file for data
# Method from : http://www.xavierdupre.fr/app/ensae_teaching_cs/helpsphinx/notebooks/prepare_data_2017.html

FILE_01_trim = "./Data/Trimester_01_2020.csv"
data_01_trim = pd.read_csv(FILE_01_trim, encoding="utf-8", low_memory=False, error_bad_lines=False)
print(FILE_01_trim, ' : ', os.stat(FILE_01_trim).st_size / 2**20, 'Mo, ', data_01_trim.shape)

FILE_02_trim = "./Data/Trimester_02_2020.csv"
data_02_trim = pd.read_csv(FILE_02_trim, encoding="utf-8", low_memory=False, error_bad_lines=False)
print(FILE_02_trim, ' : ', os.stat(FILE_02_trim).st_size / 2**20, 'Mo, ', data_02_trim.shape)

FILE_03_trim = "./Data/Trimester_03_2020.csv"
data_03_trim = pd.read_csv(FILE_03_trim, encoding="utf-8", low_memory=False, error_bad_lines=False)
print(FILE_03_trim, ' : ', os.stat(FILE_03_trim).st_size / 2**20, 'Mo, ', data_03_trim.shape)

FILE_04_trim = "./Data/Trimester_04_2020.csv"
data_04_trim = pd.read_csv(FILE_04_trim, encoding="utf-8", low_memory=False, error_bad_lines=False)
print(FILE_04_trim, ' : ', os.stat(FILE_04_trim).st_size / 2**20, 'Mo, ', data_04_trim.shape)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


./Data/Trimester_01_2020.csv  :  65.8931360244751 Mo,  (28150, 14)
./Data/Trimester_02_2020.csv  :  64.53187656402588 Mo,  (27350, 14)
./Data/Trimester_03_2020.csv  :  60.011178970336914 Mo,  (25141, 14)
./Data/Trimester_04_2020.csv  :  49.752318382263184 Mo,  (20760, 14)


In [6]:
DataRaw = pd.concat([data_01_trim, data_02_trim, data_03_trim, data_04_trim], axis = 0, ignore_index=True)
DataRaw['CreationDate'] = DataRaw['CreationDate'].astype("datetime64")
DataRaw['ClosedDate'] = DataRaw['ClosedDate'].astype("datetime64")
DataRaw.describe(include = 'all', datetime_is_numeric=True)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Id  PostTypeId  ParentId                   CreationDate  \
count   1.014010e+05    101401.0       0.0                         101401   
unique           NaN         NaN       NaN                            NaN   
top              NaN         NaN       NaN                            NaN   
freq             NaN         NaN       NaN                            NaN   
mean    6.237847e+07         1.0       NaN  2020-06-19 02:47:10.031853824   
min     5.954924e+07         1.0       NaN            2020-01-01 00:09:38   
25%     6.077459e+07         1.0       NaN            2020-03-20 12:53:55   
50%     6.236035e+07         1.0       NaN            2020-06-13 13:22:53   
75%     6.384698e+07         1.0       NaN            2020-09-11 12:19:37   
max     6.555971e+07         1.0       NaN            2020-12-30 23:53:24   
std     1.752996e+06         0.0       NaN                            NaN   

                Score      ViewCount                                     Body  \
count   101401.000000  101401.000000                                   101401   
unique            NaN            NaN                                   101398   
top               NaN            NaN  <p>So I was given the following Grad...   
freq              NaN            NaN                                        2   
mean         0.829765     636.926095                                      NaN   
min        -24.000000      51.000000                                      NaN   
25%          0.000000      84.000000                                      NaN   
50%          0.000000     169.000000                                      NaN   
75%          1.000000     450.000000                                      NaN   
max        609.000000  414968.000000                                      NaN   
std          4.832226    3762.043428                                      NaN   

         OwnerUserId               Title    Tags    AnswerCount  \
count   9.880300e+04              101401  101401  101401.000000   
unique           NaN              101399   65155            NaN   
top              NaN  Regular Expression   <c++>            NaN   
freq             NaN                   2    1340            NaN   
mean    8.883046e+06                 NaN     NaN       1.541760   
min     9.100000e+01                 NaN     NaN       1.000000   
25%     4.906254e+06                 NaN     NaN       1.000000   
50%     1.022240e+07                 NaN     NaN       1.000000   
75%     1.291629e+07                 NaN     NaN       2.000000   
max     1.571046e+07                 NaN     NaN      51.000000   
std     4.566150e+06                 NaN     NaN       0.987643   

         CommentCount  FavoriteCount                     ClosedDate  
count   101401.000000   17663.000000                           6232  
unique            NaN            NaN                            NaN  
top               NaN            NaN                            NaN  
freq              NaN            NaN                            NaN  
mean         8.373132       1.220008  2020-07-04 14:31:35.701379840  
min          6.000000       0.000000            2020-01-01 01:36:16  
25%          6.000000       1.000000     2020-03-19 20:56:12.500000  
50%          7.000000       1.000000            2020-07-09 07:51:17  
75%          9.000000       1.000000  2020-10-08 15:33:47.249999872  
max         74.000000     179.000000            2021-12-23 22:43:59  
std          2.959853       2.213022                            NaN

In [7]:
DataRaw.head(10)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Id  PostTypeId  ParentId        CreationDate  Score  ViewCount  \
0  59549242           1       NaN 2020-01-01 00:09:38     10      14089   
1  59549292           1       NaN 2020-01-01 00:27:42      0        266   
2  59549299           1       NaN 2020-01-01 00:29:41     -2        477   
3  59549318           1       NaN 2020-01-01 00:34:43      0        375   
4  59549388           1       NaN 2020-01-01 00:58:27      0         80   
5  59549397           1       NaN 2020-01-01 01:01:55     -6         84   
6  59549477           1       NaN 2020-01-01 01:28:58      0        459   
7  59549514           1       NaN 2020-01-01 01:40:05      0       1193   
8  59549593           1       NaN 2020-01-01 02:03:35      2        427   
9  59549661           1       NaN 2020-01-01 02:28:04      1         76   

                                      Body  OwnerUserId  \
0  <p>I just started on my Flutter jour...   12634357.0   
1  <p>How can I change this so that I c...   11059320.0   
2  <p><div class="snippet" data-lang="j...   12633966.0   
3  <p>There is an issue with Bootstrap ...          NaN   
4  <p>I'm wondering why the height of f...   12069171.0   
5  <p>so I have this code that with a f...   12433880.0   
6  <p>I'm learning the C language with ...   12352162.0   
7  <p>I am getting following error whil...    2538627.0   
8  <p>I am new to ajax and was followin...    2654750.0   
9  <p>I can't figure out for the life o...   12572660.0   

                                     Title  \
0  Integrating Paypal payments in Flutt...   
1  Filter list of files using an array ...   
2  The text isn't showing up and the ba...   
3  Can someone help me fix my code issu...   
4  Why the height of my first row is mo...   
5  my program wont work properly and my...   
6  Character Constants and Initializati...   
7  CORS issue: Angular 5 on AWS S3 & Cl...   
8  Ajax with javascript not working on ...   
9  :not selector is not working as expe...   

                                      Tags  AnswerCount  CommentCount  \
0       <flutter><paypal><payment-gateway>            3             6   
1                             <powershell>            2            11   
2                              <html><css>            1            12   
3              <html><bootstrap-4><safari>            1             6   
4                              <html><css>            2             6   
5      <c++><function><segmentation-fault>            1             6   
6                <c><char><int><constants>            2             8   
7  <asp.net-core><amazon-s3><cors><angu...            2            11   
8      <javascript><php><ajax><wampserver>            1            10   
9               <javascript><jquery><html>            2             7   

   FavoriteCount          ClosedDate  
0            1.0                 NaT  
1            NaN                 NaT  
2            NaN                 NaT  
3            NaN                 NaT  
4            NaN                 NaT  
5            NaN 2020-01-01 01:36:16  
6            NaN                 NaT  
7            0.0                 NaT  
8            NaN                 NaT  
9            NaN                 NaT

In [8]:
print(DataRaw.loc[7,'Title'])
print(DataRaw.loc[7,'Body'])

CORS issue: Angular 5 on AWS S3 & Cloudfront and .net core webapi on IIS10 EC 2 windows server 2019
<p>I am getting following error while accessing Angular app through browser (chrome/Edge/Firefox/Opera). <em><strong>API request works on direct calls from well through Postman/Fiddler.</strong></em></p>
<p>So i think there something between Cloudfront and EC2 calls and CORS policy</p>
<p><a href="https://i.stack.imgur.com/hsxeF.png" rel="nofollow noreferrer"><img src="https://i.stack.imgur.com/hsxeF.png" alt="enter image description here" /></a></p>
<p><a href="https://i.stack.imgur.com/TD3qQ.png" rel="nofollow noreferrer"><img src="https://i.stack.imgur.com/TD3qQ.png" alt="enter image description here" /></a></p>
<p>Following is my set up.</p>
<p><em><strong>Angular Setup:</strong></em></p>
<ul>
<li>S3 Bucket with Public access Policy</li>
<li>Cloudfront with Behavior whitelisting Headers</li>
</ul>
<p><a href="https://i.stack.imgur.com/JTbgd.png" rel="nofollow noreferrer"><img src="ht

In [ ]:
qual = ['Body', 'Title', 'Tags']
df = DataRaw[qual]
df.loc[:,'Tags'] = df.loc[:,'Tags'].apply(lambda x: x.replace('<', '')).apply(lambda x: x[:-1].split('>'))
df.describe(include = 'all', datetime_is_numeric=True)

In [132]:
df = DataRaw.copy()
soup = BeautifulSoup(df.loc[48325,'Body'], 'html.parser')
text = soup.get_text()
text

"I am writing APIs in NestJS which have a set of common headers. I decided to use interceptors in order to append headers to outgoing requests. The headers do not get appended to the request and hence the request keeps on failing.\nInterceptor\nimport * as utils from '../utils/utils';\nimport {\n  CallHandler,\n  ExecutionContext,\n  Injectable,\n  NestInterceptor\n} from '@nestjs/common';\nimport { HEADERS } from '../middlewares/headers.constant';\nimport { Observable } from 'rxjs';\nimport { Request } from 'express';\nimport { DATA_PARTITION_ID } from '../app.constants';\n\n@Injectable()\nexport class HeadersInterceptor implements NestInterceptor {\n  intercept(context: ExecutionContext, next: CallHandler): Observable<void> {\n    const ctx = context.switchToHttp();\n    const request: Request = ctx.getRequest();\n\n    this.setHeaders(request);\n\n    return next.handle();\n  }\n\n  private setHeaders(request): void {\n    this.updateHeaders(request, HEADERS.ACCEPT, 'application/jso

In [133]:
selection = ['NN', 'NNS', 'NNP', 'NNPS']
punct = string.punctuation
punct_space = " "*len(punct)
digits_space = " "*len(string.digits)
stop_words = set(nltk.corpus.stopwords.words('english'))

text = text.translate(str.maketrans(punct, punct_space, ''))
text = text.translate(str.maketrans(string.digits, digits_space, ''))
text = text.encode('ascii',errors='ignore').decode('ascii')

while '  ' in text:
        text = text.replace('  ', ' ')

text
# tokens = nltk.word_tokenize(text)
# tagged = nltk.pos_tag(tokens)
# tagged

# vec = [token.lower() for (token, tag) in tagged if (tag in selection) & (len(token) > 1)& (token not in stop_words)]
# vec

'I am writing APIs in NestJS which have a set of common headers I decided to use interceptors in order to append headers to outgoing requests The headers do not get appended to the request and hence the request keeps on failing \nInterceptor\nimport as utils from utils utils \nimport \n CallHandler \n ExecutionContext \n Injectable \n NestInterceptor\n from nestjs common \nimport HEADERS from middlewares headers constant \nimport Observable from rxjs \nimport Request from express \nimport DATA PARTITION ID from app constants \n\n Injectable \nexport class HeadersInterceptor implements NestInterceptor \n intercept context ExecutionContext next CallHandler Observable void \n const ctx context switchToHttp \n const request Request ctx getRequest \n\n this setHeaders request \n\n return next handle \n \n\n private setHeaders request void \n this updateHeaders request HEADERS ACCEPT application json \n this updateHeaders request HEADERS CONTENT TYPE application json \n this updateHeaders re

In [81]:
stop_words = set(nltk.corpus.stopwords.words('english'))
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 'r

In [5]:
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package punkt to C:\Users\Blaise-
[nltk_data]     Maël\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\Blaise-Maël\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [30]:
ps = nltk.stem.PorterStemmer()
lemmatizer = nltk.stem.WordNetLemmatizer()

tokens = nltk.word_tokenize(text)
tokens = [ps.stem(tok) for tok in tokens]

tagged = nltk.pos_tag(tokens)
tagged

[('i', 'NNS'),
 ('have', 'VBP'),
 ('thi', 'VBN'),
 ('method', 'NN'),
 ('but', 'CC'),
 ('i', 'NN'),
 ('am', 'VBP'),
 ('not', 'RB'),
 ('abl', 'JJ'),
 ('to', 'TO'),
 ('figur', 'VB'),
 ('out', 'RP'),
 ('which', 'WDT'),
 ('paramet', 'NN'),
 ('should', 'MD'),
 ('i', 'VB'),
 ('pass', 'NN'),
 ('in', 'IN'),
 ('postman', 'NN'),
 ('to', 'TO'),
 ('execut', 'VB'),
 ('thi', 'JJ'),
 ('method', 'NN'),
 ('.', '.'),
 ('i', 'VB'),
 ('sent', 'VBD'),
 ('the', 'DT'),
 ('bodi', 'NN'),
 ('in', 'IN'),
 ('form-data', 'NN'),
 ('of', 'IN'),
 ('postman', 'NN'),
 ('and', 'CC'),
 ('content-typ', 'NN'),
 ('is', 'VBZ'),
 ('multipart/form-data', 'JJ'),
 ('.', '.'),
 ('later', 'RB'),
 ('i', 'RB'),
 ('have', 'VBP'),
 ('to', 'TO'),
 ('send', 'VB'),
 ('the', 'DT'),
 ('file', 'NN'),
 ('as', 'RB'),
 ('well', 'RB'),
 ('that', 'IN'),
 ("'s", 'VBZ'),
 ('whi', 'NN'),
 ('i', 'NN'),
 ('am', 'VBP'),
 ('use', 'RB'),
 ('form-data', 'JJ'),
 ('.', '.'),
 ('searchstr', 'NN'),
 ('is', 'VBZ'),
 ('come', 'VBN'),
 ('out', 'RP'),
 ('be', 'VB

In [31]:
selection = ['NN', 'NNS', 'NNP', 'NNPS']
punct_space = " "*len(string.punctuation)
digits_space = " "*len(string.digits)

ps = nltk.stem.PorterStemmer()
lemmatizer = nltk.stem.WordNetLemmatizer()

text = text.translate(str.maketrans(string.punctuation, punct_space, ''))
text = text.translate(str.maketrans(string.digits, digits_space, ''))
while '  ' in text:
        text = text.replace('  ', ' ')
        
tokens = nltk.word_tokenize(text)
tagged = nltk.pos_tag(tokens)
tagged

vec = [token.lower() for (token, tag) in tagged if (tag in selection) & (len(token) > 1)]
vec = [ps.stem(tok) for tok in vec]
vec

['method',
 'paramet',
 'postman',
 'method',
 'bodi',
 'data',
 'postman',
 'content',
 'type',
 'form',
 'data',
 'file',
 'form',
 'data',
 'searchstr',
 'code',
 'valu',
 'calendar',
 'method',
 'requestmethod',
 'post',
 'farecalendarrespons',
 'getcalendar',
 'requestparam',
 'valu',
 'searchstr',
 'string',
 'httpservletrequest',
 'httprequest',
 'except',
 'calendarrequest',
 'calenderrequest',
 'return',
 'farecalendarhandl',
 'builder',
 'httprequest',
 'httprequest',
 'request',
 'build',
 'getrespons']

In [103]:
selection = ['NN', 'NNS', 'NNP', 'NNPS']

vec = [token.lower() for (token, tag) in tagged if tag in selection]
vec

['method',
 'parameters',
 'postman',
 'method',
 'body',
 'data',
 'postman',
 'content',
 'type',
 'form',
 'data',
 'file',
 'form',
 'data',
 'searchstring',
 'code',
 'value',
 'calendar',
 'method',
 'requestmethod',
 'post',
 'farecalendarresponse',
 'getcalendar',
 'requestparam',
 'value',
 'searchstring',
 'string',
 'httpservletrequest',
 'httprequest',
 'exception',
 'calendarrequest',
 'calenderrequest',
 'return',
 'farecalendarhandler',
 'builder',
 'httprequest',
 'httprequest',
 'request',
 'build',
 'getresponse']

In [65]:
spell = SpellChecker()
[spell.correction(word) for word in vec]

['docker',
 'containers',
 'mac',
 'host',
 'container',
 'docker',
 'hub',
 'container',
 'docker',
 'hub',
 'containers',
 'access',
 'jenkins',
 'host',
 '//localhost:8080/',
 'access',
 'sonarqube',
 '//localhost:9000/',
 'jenkins',
 'container',
 'docker',
 'ad',
 'up',
 'jenkins/jenkins',
 'sonarqube',
 'container',
 'docker',
 'ad',
 'up',
 'sonarqube',
 'container',
 'communicate',
 'ip',
 'address',
 'container',
 'container',
 'ip',
 'address',
 'container',
 'docker',
 'inspect',
 'format',
 'container_name_or_id',
 'ip',
 'address',
 'jenkins',
 'container',
 'sonarqube',
 'container',
 'access',
 'jenkins',
 'container',
 'host',
 '//172.17.0.2:8080',
 'request',
 'timeout',
 'thing',
 'access',
 'sonarqube',
 'container',
 'host',
 '//172.17.0.3:9000',
 'behavior',
 'access',
 'container',
 'host',
 'ip',
 'address',
 'container',
 'jenkins',
 'access',
 'container',
 'sonarqube',
 'ip',
 'address']

In [8]:
# df.loc[0,'Title']
soup = BeautifulSoup(df.loc[65,'Title'], 'html.parser')
title = soup.get_text()
title

'Puppeteer Error: Chromium revision is not downloaded'

In [8]:
def set_str(row, bar=None, lenght = None, lemmatizer = None, stem = None):
    errors_counts = 0
    selection = ['NN', 'NNS', 'NNP', 'NNPS']
    stop_words = set(nltk.corpus.stopwords.words('english'))
    
    punct = string.punctuation
    punct_space = " "*len(string.punctuation)
    
    digits_space = " "*len(string.digits)

    if lenght is not None:
        progress = row.name / lenght
    else:
        progress = 1
    
    vec_title = []
    vec_body = []
        
    title = BeautifulSoup(row['Title'], 'html.parser').get_text()
    body = BeautifulSoup(row['Body'], 'html.parser').get_text()
    
    title = title.translate(str.maketrans(punct, punct_space,''))
    body = body.translate(str.maketrans(punct, punct_space,''))

    title = title.translate(str.maketrans(string.digits, digits_space,''))
    body = body.translate(str.maketrans(string.digits, digits_space,''))
    
    title = title.encode('ascii',errors='ignore').decode('ascii')
    body = body.encode('ascii',errors='ignore').decode('ascii')

    while '  ' in title:
        title = title.replace('  ', ' ')

    while '  ' in body:
        body = body.replace('  ', ' ')
                
    try:
        if detect(body) == 'en':

            # Suppression des mots qui ne sont pas des noms
            tok_title = nltk.word_tokenize(title)
            tok_body = nltk.word_tokenize(body)

            tag_title = nltk.pos_tag(tok_title)
            tag_body = nltk.pos_tag(tok_body)

            vec_title = [lemmatizer.lemmatize(token.lower()) for (token, tag) in tag_title if (tag in selection) & (len(token) > 1)& (token not in stop_words)]
            vec_body = [lemmatizer.lemmatize(token.lower()) for (token, tag) in tag_body if (tag in selection) & (len(token) > 1) & (token not in stop_words)]
        
    except:
        print("\nThis body and langag detect error: \n {0:s}\n {1:s}\n".format(row['Body'], body))
        errors_counts += 0
        
    row['Title'] = vec_title
    row['Body'] = vec_body

    if bar is not None:
        bar.update_progress(progress)
        
    return row

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [7]:
DetectorFactory.seed = 0
# nltk.download('stopwords')
# nltk.download('wordnet')

ps = nltk.stem.PorterStemmer()
lemmatizer = nltk.stem.WordNetLemmatizer()

ProgressBar().register()
ddata = dd.from_pandas(DataRaw, npartitions=4*multiprocessing.cpu_count())
with ProgressBar():
    DataModel = ddata.map_partitions(
        lambda df: df.apply(
            set_str,
            args = (None, len(df), lemmatizer), axis=1)
    ).compute(scheduler='processes')

DataModel = DataModel[DataModel.astype(str)['Title'] != '[]'] 

DataModel.describe(include='all', datetime_is_numeric=True)

[########################################] | 100% Completed | 16min 27.5s
[########################################] | 100% Completed | 16min 27.6s


Id  PostTypeId  ParentId                   CreationDate  \
count   1.008800e+05    100880.0       0.0                         100880   
unique           NaN         NaN       NaN                            NaN   
top              NaN         NaN       NaN                            NaN   
freq             NaN         NaN       NaN                            NaN   
mean    6.237787e+07         1.0       NaN  2020-06-19 01:54:48.374841088   
min     5.954924e+07         1.0       NaN            2020-01-01 00:09:38   
25%     6.077349e+07         1.0       NaN  2020-03-20 11:45:01.249999872   
50%     6.235985e+07         1.0       NaN     2020-06-13 12:34:21.500000   
75%     6.384517e+07         1.0       NaN  2020-09-11 10:19:59.249999872   
max     6.555971e+07         1.0       NaN            2020-12-30 23:53:24   
std     1.752863e+06         0.0       NaN                            NaN   

                Score      ViewCount                                     Body  \
count   100880.000000  100880.000000                                   100880   
unique            NaN            NaN                                   100877   
top               NaN            NaN  [gradedactivity, class, class, grade...   
freq              NaN            NaN                                        2   
mean         0.828648     638.399375                                      NaN   
min        -24.000000      51.000000                                      NaN   
25%          0.000000      84.000000                                      NaN   
50%          0.000000     169.000000                                      NaN   
75%          1.000000     452.000000                                      NaN   
max        609.000000  414968.000000                                      NaN   
std          4.803132    3771.002179                                      NaN   

         OwnerUserId       Title    Tags    AnswerCount   CommentCount  \
count   9.830300e+04      100880  100880  100880.000000  100880.000000   
unique           NaN       96017   64898            NaN            NaN   
top              NaN  [function]   <c++>            NaN            NaN   
freq             NaN          99    1325            NaN            NaN   
mean    8.876590e+06         NaN     NaN       1.541564       8.372224   
min     9.100000e+01         NaN     NaN       1.000000       6.000000   
25%     4.889224e+06         NaN     NaN       1.000000       6.000000   
50%     1.021119e+07         NaN     NaN       1.000000       7.000000   
75%     1.291349e+07         NaN     NaN       2.000000       9.000000   
max     1.571046e+07         NaN     NaN      51.000000      74.000000   
std     4.566554e+06         NaN     NaN       0.988067       2.958867   

        FavoriteCount                     ClosedDate  
count    17551.000000                           6167  
unique            NaN                            NaN  
top               NaN                            NaN  
freq              NaN                            NaN  
mean         1.220956  2020-07-04 17:08:41.918274560  
min          0.000000            2020-01-01 01:36:16  
25%          1.000000     2020-03-19 18:23:26.500000  
50%          1.000000            2020-07-09 13:18:47  
75%          1.000000            2020-10-08 19:45:45  
max        179.000000            2021-12-23 22:43:59  
std          2.218250                            NaN

In [ ]:
bar = progress_bar(10, 'treatement', 1e-2)
# bar = progress_bar(10, 'treatement', time_lim=1)
bar.set_progress(0)

lemmatizer = nltk.stem.WordNetLemmatizer()
DataModel = DataRaw.apply(set_str, args=(bar, len(DataRaw), lemmatizer), axis = 1)
DataModel = DataModel[DataModel.astype(str)['Title'] != '[]']
bar.update_progress(1)

DataModel.describe(include='all', datetime_is_numeric=True)

Progress treatement: [###-------------------------------------] 8.00% 0:01:58.707909
This body and langag detect error: 
 <p>I am making a single page in Angular 6. It a simple page and I would like to highlight <code>navbar</code> depending on scroll.</p>

<p>here is my code:</p>

<p><div class="snippet" data-lang="js" data-hide="false" data-console="true" data-babel="false">
<div class="snippet-code">
<pre class="snippet-code-css lang-css prettyprint-override"><code>.sticky {
  position: sticky;
  top: 0;
}
#i ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: blue;
}

#i li {
  float: left;
}

#i li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

#i li a:hover {
  border-radius: 0px 0px 10px 10px;
  background-color: rgb(43, 137, 226);
}

/* #i {
  margin: 0px 0px 40px 0px;
} */

#footer-id {
  background-color:blue;
}</code></pre>
<pre class="snippet-code-html lang-html prett

Progress treatement: [####------------------------------------] 9.00% 0:02:13.485168
This body and langag detect error: 
 <p>I have a problem with LazyInitializationException and I don't know how to fix it.</p>

<pre><code>for (Long id : employeeIds)
    {
        List&lt;ProjectEmployee&gt; projectEmployeeList = projectEmployeeService.findProjectEmployeesWithinDates(id,
                startDate, endDate);

        // if no data, then continue with next employee
        if (projectEmployeeList.isEmpty())
        {
            continue;
        }

        gridCreated = true;

        Employee employee = projectEmployeeList.get(0).getEmployee();
        Label titleLabel = new Label(employee.getPerson().getSurname() + " " + employee.getPerson().getName() + " ["
                                     + employee.getRole().getHumanizedRole() + "]");
        titleLabel.setStyleName("header-bold");

        ProjectEmployeePanel projectEmployeePanel = new ProjectEmployeePanel(id, startDate, endD

Progress treatement: [####------------------------------------] 10.00% 0:02:29.195141

In [9]:
FILE_Model = "./Data/Model_v2.csv"
# DataModel.to_csv(FILE_Model, index=False, doublequote=False)

DataModel = pd.read_csv(FILE_Model, encoding="utf-8", low_memory=False, doublequote=False, error_bad_lines=False)
DataModel['Body'] = DataModel['Body'].astype('str')
DataModel['Body'] = DataModel.Body.apply(
    lambda x: 
    x.replace('\'', '')
    .replace('[', '')
    .replace(']', '')
).apply(
    lambda x: x[:].split(', ')
)
DataModel['Title'] = DataModel.Title.apply(
    lambda x: 
    x.replace('\'', '')
    .replace('[', '')
    .replace(']', '')
).apply(
    lambda x: x[:].split(', ')
)

print(DataModel['Body'].dtypes)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


object


In [7]:
multiprocessing.cpu_count()

8

In [10]:
DataModel['Tags'] = DataModel['Tags'].apply(lambda x: x.replace('<', '')).apply(lambda x: x[:-1].split('>'))

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [9]:
DataModel

Id  PostTypeId  ParentId         CreationDate  Score  ViewCount  \
0       59549242           1       NaN  2020-01-01 00:09:38     10      14089   
1       59549292           1       NaN  2020-01-01 00:27:42      0        266   
2       59549299           1       NaN  2020-01-01 00:29:41     -2        477   
3       59549318           1       NaN  2020-01-01 00:34:43      0        375   
4       59549388           1       NaN  2020-01-01 00:58:27      0         80   
...          ...         ...       ...                  ...    ...        ...   
100884  65514630           1       NaN  2020-12-30 23:02:42     -2         96   
100885  65514632           1       NaN  2020-12-30 23:02:54     -2         57   
100886  65514712           1       NaN  2020-12-30 23:13:53      0        265   
100887  65514890           1       NaN  2020-12-30 23:37:04      1        225   
100888  65515004           1       NaN  2020-12-30 23:53:24      0        102   

                                           Body  OwnerUserId  \
0       [flutter, journey, need, payment, fl...   12634357.0   
1       [cycle, list, file, array, expressio...   11059320.0   
2       [body, background, color, size, px, ...   12633966.0   
3       [issue, bootstrap, safari, mac, col,...          NaN   
4       [height, row, march, product, jiko, ...   12069171.0   
...                                         ...          ...   
100884  [problem, piece, chessboard, king, w...   14687335.0   
100885  [middle, calendar, javascript, date,...          NaN   
100886  [join, table, problem, table, table,...   15040818.0   
100887  [version, function, isalpha, work, l...       4668.0   
100888  [image, command, discord, j, bot, er...   14722081.0   

                                          Title  \
0                       [payment, flutter, app]   
1       [filter, list, file, array, expression]   
2        [text, background, color, text, color]   
3       [someone, code, issue, bootstrap, sa...   
4                            [height, row, row]   
...                                         ...   
100884                   [program, queen, king]   
100885                   [calendar, javascript]   
100886                   [jpa, jpql, statement]   
100887  [glibc, isalpha, function, u, utf, l...   
100888  [problem, reddit, command, discord, ...   

                                       Tags  AnswerCount  CommentCount  \
0        [flutter, paypal, payment-gateway]            3             6   
1                              [powershell]            2            11   
2                               [html, css]            1            12   
3               [html, bootstrap-4, safari]            1             6   
4                               [html, css]            2             6   
...                                     ...          ...           ...   
100884                                  [c]            1            10   
100885                         [javascript]            2             6   
100886  [java, mysql, hibernate, jpa, jpql]            2             7   
100887              [c, locale, glibc, utf]            1             8   
100888                         [discord.js]            1             6   

        FavoriteCount ClosedDate  
0                 1.0        NaN  
1                 NaN        NaN  
2                 NaN        NaN  
3                 NaN        NaN  
4                 NaN        NaN  
...               ...        ...  
100884            NaN        NaN  
100885            NaN        NaN  
100886            NaN        NaN  
100887            NaN        NaN  
100888            NaN        NaN  

[100889 rows x 14 columns]

In [74]:
type(DataModel.loc[490, 'Body'])

list

In [10]:
feat = 'Body'

lookedfor = [['aaiaaaiaaaiaaaiaaaiaaaiaaaiaaaiaaaiaaaiaaaiaaamaaaiaaaiaaa']]
# lookedfor = ['abcdefghijklmonpqrstuvwxyz']
# lookedfor = [string.punctuation]
def check_words_list(column, lookedfor):
    return list(set(column) & set(lookedfor))
    
test = pd.DataFrame(DataModel[feat].apply(check_words_list, args=(lookedfor)))
test = test[test.astype(str)[feat] != '[]']
test

Empty DataFrame
Columns: [Body]
Index: []

In [170]:
DataRaw.loc[490, 'Body']

'<p>I am trying to send a picture from my Pi camera to a flask web server. When I encode the image Base64 it doesn\'t seem to produce a valid image.</p>\n\n<p>I can take the picture and process it through <code>opencv</code>. The Base64 encoded image is passed to the web page, but the string sent is not a valid image. To prove this I have saved the image and processed it with an online Base64 converter. Pasting this string into the web page shows the image. </p>\n\n<pre><code>def Take_Picture(camera):\n    stream = io.BytesIO()                                           # saving the picture to an in-program stream \n    camera.resolution = (160,120)                                   # set resolution\n    camera.capture(stream, format=\'jpeg\', use_video_port=True)      # capture into stream\n    mydata = np.fromstring(stream.getvalue(), dtype=np.uint8)       # convert image into numpy array\n    img = cv2.imdecode(mydata, -1)                                  # to opencv image\n    data 

In [171]:
DataRaw.loc[48325, 'Body']

"<p>I am writing APIs in NestJS which have a set of common headers. I decided to use interceptors in order to append headers to outgoing requests. The headers do not get appended to the request and hence the request keeps on failing.</p>\n<p><strong>Interceptor</strong></p>\n<pre><code>import * as utils from '../utils/utils';\nimport {\n  CallHandler,\n  ExecutionContext,\n  Injectable,\n  NestInterceptor\n} from '@nestjs/common';\nimport { HEADERS } from '../middlewares/headers.constant';\nimport { Observable } from 'rxjs';\nimport { Request } from 'express';\nimport { DATA_PARTITION_ID } from '../app.constants';\n\n@Injectable()\nexport class HeadersInterceptor implements NestInterceptor {\n  intercept(context: ExecutionContext, next: CallHandler): Observable&lt;void&gt; {\n    const ctx = context.switchToHttp();\n    const request: Request = ctx.getRequest();\n\n    this.setHeaders(request);\n\n    return next.handle();\n  }\n\n  private setHeaders(request): void {\n    this.updateH

## 2) Analyse du dataset

### 2.A) Analyse univariée 

In [11]:
DataModel.plot(x='Id', y='AnswerCount', kind='scatter')

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<AxesSubplot:xlabel='Id', ylabel='AnswerCount'>

In [12]:
DataModel.plot(x='Id', y='CommentCount', kind='scatter')

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

<AxesSubplot:xlabel='Id', ylabel='CommentCount'>

In [13]:
DataModel = DataModel[DataModel['CommentCount'] > 5]
DataModel = DataModel.reset_index()
DataModel

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


index        Id  PostTypeId  ParentId         CreationDate  Score  \
0            0  59549242           1       NaN  2020-01-01 00:09:38     10   
1            1  59549292           1       NaN  2020-01-01 00:27:42      0   
2            2  59549299           1       NaN  2020-01-01 00:29:41     -2   
3            3  59549318           1       NaN  2020-01-01 00:34:43      0   
4            4  59549388           1       NaN  2020-01-01 00:58:27      0   
...        ...       ...         ...       ...                  ...    ...   
100884  100884  65514630           1       NaN  2020-12-30 23:02:42     -2   
100885  100885  65514632           1       NaN  2020-12-30 23:02:54     -2   
100886  100886  65514712           1       NaN  2020-12-30 23:13:53      0   
100887  100887  65514890           1       NaN  2020-12-30 23:37:04      1   
100888  100888  65515004           1       NaN  2020-12-30 23:53:24      0   

        ViewCount                                     Body  OwnerUserId  \
0           14089  [flutter, journey, need, payment, fl...   12634357.0   
1             266  [cycle, list, file, array, expressio...   11059320.0   
2             477  [body, background, color, size, px, ...   12633966.0   
3             375  [issue, bootstrap, safari, mac, col,...          NaN   
4              80  [height, row, march, product, jiko, ...   12069171.0   
...           ...                                      ...          ...   
100884         96  [problem, piece, chessboard, king, w...   14687335.0   
100885         57  [middle, calendar, javascript, date,...          NaN   
100886        265  [join, table, problem, table, table,...   15040818.0   
100887        225  [version, function, isalpha, work, l...       4668.0   
100888        102  [image, command, discord, j, bot, er...   14722081.0   

                                          Title  \
0                       [payment, flutter, app]   
1       [filter, list, file, array, expression]   
2        [text, background, color, text, color]   
3       [someone, code, issue, bootstrap, sa...   
4                            [height, row, row]   
...                                         ...   
100884                   [program, queen, king]   
100885                   [calendar, javascript]   
100886                   [jpa, jpql, statement]   
100887  [glibc, isalpha, function, u, utf, l...   
100888  [problem, reddit, command, discord, ...   

                                       Tags  AnswerCount  CommentCount  \
0        [flutter, paypal, payment-gateway]            3             6   
1                              [powershell]            2            11   
2                               [html, css]            1            12   
3               [html, bootstrap-4, safari]            1             6   
4                               [html, css]            2             6   
...                                     ...          ...           ...   
100884                                  [c]            1            10   
100885                         [javascript]            2             6   
100886  [java, mysql, hibernate, jpa, jpql]            2             7   
100887              [c, locale, glibc, utf]            1             8   
100888                         [discord.js]            1             6   

        FavoriteCount ClosedDate  
0                 1.0        NaN  
1                 NaN        NaN  
2                 NaN        NaN  
3                 NaN        NaN  
4                 NaN        NaN  
...               ...        ...  
100884            NaN        NaN  
100885            NaN        NaN  
100886            NaN        NaN  
100887            NaN        NaN  
100888            NaN        NaN  

[100889 rows x 15 columns]

In [147]:
# DataRaw.loc[0,'Body']

In [22]:
top = 50
# count, words = exp.most_common_words(DataModel['Body'], ', ', top)
# pd.DataFrame([words, count])
df = exp.check_common_words(DataModel['Body'], ', ', top)


D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)


Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

On regarde ici les 50 mots les plus fréquent dans le corps de text et aucun n'est étrange.

In [26]:
df = DataModel.copy()
feat = 'Body'
bins = 500
binwidth = 1
ex_thr = 0.1

Lenght = []
integral = 0
bin_min = 0
int_min = 0 
bin_max = 0
int_max = 0
min_done = False
max_done = False

fig = plt.figure(figsize=(10,5))
plt.title('Lenght of {0:s}'.format(feat))
plt.xlabel('Number of words')
plt.ylabel('Number of documents')

Lenght = df[feat].apply(lambda x : len(x) )
auc = len(Lenght)
mean = statistics.mean(Lenght)
stdev = statistics.stdev(Lenght)
print('Mean of distribution = {0:.2f}({1:.2f})'.format(mean,stdev))
print('Total integral : {0:.2f}'.format(auc))

# y, x, _ = plt.hist(Lenght, bins=range(min(Lenght), max(Lenght) + binwidth, binwidth))
y, x, _ = plt.hist(Lenght, bins=bins, range=(0, bins))

for ibin, content in enumerate(y):
    integral += content
#     print(integral, content, auc, (1 - ex_thr)*auc)
    if min_done == True and max_done == True:
        break
    if integral > (1 - ex_thr)*auc and max_done == False:
        bin_max = x[ibin]
        int_max = integral
        max_done = True
    if integral > ex_thr*auc and min_done == False:
        bin_min = x[ibin]
        int_min = integral
        min_done = True
    
print('{0:.0f}% integral : {1:.2f} at {2:.0f}'.format((1-ex_thr)*100, int_max, bin_max))
print('{0:.0f}% integral : {1:.2f} at {2:.0f}'.format(ex_thr*100, int_min, bin_min))
print('Max of distribution = {0:.2f}({1:.2f})'.format(max(y),np.argmax(y)))
    
plt.axvline(mean, color='red', linestyle='dashed', linewidth=2)
plt.text(mean, Lenght[int(mean)], 'Mean')

plt.axvline(np.argmax(y), color='black', linestyle='dashed', linewidth=2)
plt.text(np.argmax(y), max(y), 'Max')

plt.axvline(mean+stdev, color='blue', linestyle='dashed', linewidth=1)
plt.axvline(mean-stdev, color='blue', linestyle='dashed', linewidth=1)
plt.text(mean+stdev, x[int(mean+stdev)], 'Mean +/- stdev')

plt.axvline(bin_max, color='green', linestyle='dashed', linewidth=1)
plt.text(bin_max, 0.8*max(y), '{0:.1f}-threshold'.format((1-ex_thr)*100))
plt.axvline(bin_min, color='green', linestyle='dashed', linewidth=1)
plt.text(bin_min, 0.8*max(y), '{0:.1f}-threshold'.format(ex_thr*100))
plt.show()

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Mean of distribution = 117.09(164.89)
Total integral : 100889.00
90% integral : 90837.00 at 243
10% integral : 10871.00 at 22
Max of distribution = 1002.00(37.00)


Ici la moyenne est décentré par rapport à mod de la gaussienne. On voie que si on prend la moyenne plus ou moins 1 stdev on dépasse les 90% de la statistique. On préfèrera ici prendre un seuil qui correspond à 90% de la statistique soit les corps de text ayant moins de 243 mots

In [27]:
def select_row(row, feat, minimum, maximum):
    if minimum >= len(row[feat]) or len(row[feat]) >= maximum:
        row[feat] = np.nan
    return row

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [28]:
df = DataModel.copy()
feat = 'Body'
maximum = 243
minimum = 22

# ddata = dd.from_pandas(df, npartitions=4*multiprocessing.cpu_count())
# with ProgressBar():
#     df = ddata.map_partitions(
#         lambda df : df.apply(
#             select_row,
#             args=(feat, minimum, maximum),
#             axis=1
#         )
#     ).compute(scheduler='processes')

df = df.apply(select_row,
            args=(feat, minimum, maximum),
            axis=1)

DataReduced = df.dropna(subset=[feat])
DataReduced.describe()

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


index            Id  PostTypeId  ParentId         Score  \
count   79896.000000  7.989600e+04     79896.0       0.0  79896.000000   
mean    50574.285784  6.238600e+07         1.0       NaN      0.806198   
std     29129.211695  1.753194e+06         0.0       NaN      4.325216   
min         1.000000  5.954929e+07         1.0       NaN    -12.000000   
25%     25397.750000  6.078524e+07         1.0       NaN      0.000000   
50%     50638.500000  6.237202e+07         1.0       NaN      0.000000   
75%     75784.250000  6.385348e+07         1.0       NaN      1.000000   
max    100888.000000  6.555971e+07         1.0       NaN    609.000000   

           ViewCount   OwnerUserId   AnswerCount  CommentCount  FavoriteCount  
count   79896.000000  7.790200e+04  79896.000000  79896.000000   13788.000000  
mean      595.719360  8.801545e+06      1.533293      8.356639       1.195677  
std      3194.528955  4.582230e+06      0.944624      2.924564       2.157538  
min        51.000000  9.100000e+01      1.000000      6.000000       0.000000  
25%        84.000000  4.763651e+06      1.000000      6.000000       1.000000  
50%       166.000000  1.008557e+07      1.000000      7.000000       1.000000  
75%       437.000000  1.288766e+07      2.000000      9.000000       1.000000  
max    339670.000000  1.571046e+07     51.000000     74.000000     179.000000

In [29]:
top = 50
count, words = exp.most_common_words(DataModel['Title'], ', ', top)
pd.DataFrame([words, count])

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0      1         2      3       4      5     6     7       8       9   \
0  file  value  function  error  python  array  data  list  object  string   
1  6256   6190      6039   6014    5305   5112  4484  3717    3147    3046   

      10    11    12      13    14          15      16    17       18    19  \
0  class  code  java  number  type  javascript  column   way  element   sql   
1   3006  2717  2703    2562  2471        2359    2298  2155     2111  2085   

       20    21    22    23     24     25     26    27    28    29     30  \
0  method  loop  time  json  image  table  react   php     j   api  query   
1    2082  2059  2049  1959   1935   1812   1760  1737  1711  1627   1569   

       31    32    33        34    35    36      37    38      39    40  \
0  server  line   app  variable   row  name  script  text  access  date   
1    1554  1536  1521      1520  1511  1488    1486  1452    1421  1420   

      41       42       43        44    45      46    47    48    49  
0  input  problem  laravel  property  user  return  page  form  html  
1   1370     1354     1345      1327  1266    1261  1254  1239  1229

In [30]:
df = DataReduced.copy()
feat = 'Title'
bins = 500
binwidth = 1
ex_thr = 0.1

Lenght = []
integral = 0
bin_min = 0
int_min = 0 
bin_max = 0
int_max = 0
min_done = False
max_done = False

fig = plt.figure(figsize=(10,5))
plt.title('Lenght of {0:s}'.format(feat))
plt.xlabel('Number of words')
plt.ylabel('Number of documents')

Lenght = df[feat].apply(lambda x : len(x) )
auc = len(Lenght)
mean = statistics.mean(Lenght)
stdev = statistics.stdev(Lenght)
print('Mean of distribution = {0:.2f}({1:.2f})'.format(mean,stdev))
print('Total integral : {0:.2f}'.format(auc))

y, x, _ = plt.hist(Lenght, bins=range(min(Lenght), max(Lenght) + binwidth, binwidth))
# y, x, _ = plt.hist(Lenght, bins=bins, range=(0, bins))

for ibin, content in enumerate(y):
    integral += content
#     print(integral, content, auc, (1 - ex_thr)*auc)
    if min_done == True and max_done == True:
        break
    if integral > (1 - ex_thr)*auc and max_done == False:
        bin_max = x[ibin]
        int_max = integral
        max_done = True
    if integral > ex_thr*auc and min_done == False:
        bin_min = x[ibin]
        int_min = integral
        min_done = True
    
print('{0:.0f}% integral : {1:.2f} at {2:.0f}'.format((1-ex_thr)*100, int_max, bin_max))
print('{0:.0f}% integral : {1:.2f} at {2:.0f}'.format(ex_thr*100, int_min, bin_min))
print('Max of distribution = {0:.2f}({1:.2f})'.format(max(y),np.argmax(y)))
    
plt.axvline(mean, color='red', linestyle='dashed', linewidth=2)
plt.text(mean, x[int(mean)], 'Mean')

plt.axvline(np.argmax(y), color='black', linestyle='dashed', linewidth=2)
plt.text(np.argmax(y), max(y), 'Max')

plt.axvline(mean+stdev, color='blue', linestyle='dashed', linewidth=1)
plt.axvline(mean-stdev, color='blue', linestyle='dashed', linewidth=1)
plt.text(mean+stdev, x[int(mean+stdev)], 'Mean +/- stdev')

plt.axvline(bin_max, color='green', linestyle='dashed', linewidth=1)
plt.text(bin_max, 0.8*max(y), '{0:.1f}-threshold'.format((1-ex_thr)*100))
plt.axvline(bin_min, color='green', linestyle='dashed', linewidth=1)
plt.text(bin_min, 0.8*max(y), '{0:.1f}-threshold'.format(ex_thr*100))
plt.show()

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Mean of distribution = 4.14(1.81)
Total integral : 79896.00
90% integral : 72153.00 at 6
10% integral : 13561.00 at 2
Max of distribution = 18701.00(3.00)


Ici les deux solutions converge vers 4 +/- 2.

In [283]:
top = 50
count, words = exp.most_common_words(DataModel['Tags'], ', ', top)
pd.DataFrame([words, count])

0           1     2     3     4     5     6     7        8     9   \
0  python  javascript   c++    c#  java     c   php  html  reactjs   sql   
1   14424       12270  9579  8710  7902  5566  4679  4266     3795  3171   

        10          11      12       13    14     15       16       17  \
0  android  python-3.x  arrays  node.js   css  mysql  angular  laravel   
1     3130        3109    3098     2629  2456   2419     2019     1955   

       18    19          20    21     22     23          24      25    26  \
0  jquery     r  sql-server  json  swift  excel  typescript  pandas   vba   
1    1910  1891        1890  1872   1834   1677        1660    1636  1536   

      27    28      29         30       31      32           33    34     35  \
0  regex   ios  string  algorithm  flutter  django  spring-boot  .net  linux   
1   1463  1430    1309       1285     1267    1235         1221  1165   1140   

     36    37      38            39      40        41      42  \
0  bash  list  docker  asp.net-core  spring  firebase  vue.js   
1  1136  1056    1041           998     968       957     930   

                    43     44          45        46              47        48  \
0  amazon-web-services  numpy  postgresql  pointers  multithreading  function   
1                  900    891         884       874             837       819   

          49  
0  .net-core  
1        811

In [37]:
feat = 'Tags'
binwidth = 1
bins = 500
beacon_1 = 1000
beacon_2 = 500
beacon_3 = 100

x = []
y = []

count, words = exp.most_common_words(DataModel['Tags'], ', ', None)
auc = sum(count)

for i, value in enumerate(count):
    x.append(i)
    y.append(value/sum(count)*100)
    if value > beacon_1:
        x_1 = i
    if value > beacon_2:
        x_2 = i
    if value > beacon_3:
        x_3 = i

print('Number of tags : {0}'.format(len(words)))

fig = plt.figure(figsize=(10,5))
plt.title('{0:.0f} most frequent {1:s}'.format(bins,feat))
plt.xlabel('Tags rank')
plt.ylabel('Percent of documents')

# plt.hist(x, weights=y, bins=range(min(x), max(x) + binwidth, binwidth) )
plt.hist(x, weights=y, bins=bins, range=(0, bins))

plt.axvline(x_1, color='green', linestyle='dashed', linewidth=1)
plt.text(x_1, beacon_1/count[0], '{0}, {1}'.format(beacon_1, x_1))

plt.axvline(x_2, color='yellow', linestyle='dashed', linewidth=1)
plt.text(x_2, beacon_2/count[0], '{0}, {1}'.format(beacon_2, x_2))

plt.axvline(x_3, color='red', linestyle='dashed', linewidth=1)
plt.text(x_3, beacon_3/count[0], '{0}, {1}'.format(beacon_3, x_3))

plt.show()

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Number of tags : 16248


<ipython-input-37-74caa5f55fb9>:26: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).
  fig = plt.figure(figsize=(10,5))
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, 

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

On se fixe le minimum de docments par tag à 100, ce qui siginifie que l'on doit prendre les 369 tags les plus fréquents.

On a 16248 Tags différents dans le corpus.

In [80]:
fig = plt.figure(figsize=(10,9))
plt.bar(words, count)
plt.xticks(rotation=90)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

On regarde ici les 50 tags les plus fréquents.

In [38]:
df = DataReduced.copy()
feat = 'Tags'
bins = 6
binwidth = 1
ex_thr = 0.1

Lenght = []
integral = 0
bin_min = 0
int_min = 0 
bin_max = 0
int_max = 0
min_done = False
max_done = False

fig = plt.figure(figsize=(10,9))
plt.title('Lenght of {0:s}'.format(feat))

Lenght = df[feat].apply(lambda x : len(x) )
auc = len(Lenght)
mean = statistics.mean(Lenght)
stdev = statistics.stdev(Lenght)
print('Mean of distribution = {0:.2f}({1:.2f})'.format(mean,stdev))
print('Total integral : {0:.2f}'.format(auc))

# y, x, _ = plt.hist(Lenght, bins=range(min(Lenght), max(Lenght) + binwidth, binwidth))
y, x, _ = plt.hist(Lenght, bins=bins, range=(0, bins))

for ibin, content in enumerate(y):
    integral += content
#     print(integral, content, auc, (1 - ex_thr)*auc)
    if min_done == True and max_done == True:
        break
    if integral > (1 - ex_thr)*auc and max_done == False:
        bin_max = x[ibin]
        int_max = integral
        max_done = True
    if integral > ex_thr*auc and min_done == False:
        bin_min = x[ibin]
        int_min = integral
        min_done = True
    
print('{0:.0f}% integral : {1:.2f} at {2:.0f}'.format((1-ex_thr)*100, int_max, bin_max))
print('{0:.0f}% integral : {1:.2f} at {2:.0f}'.format(ex_thr*100, int_min, bin_min))
print('Max of distribution = {0:.2f}({1:.2f})'.format(max(y),np.argmax(y)))
    
plt.axvline(mean, color='red', linestyle='dashed', linewidth=2)
plt.text(mean, x[int(mean)], 'Mean')

plt.axvline(np.argmax(y), color='black', linestyle='dashed', linewidth=2)
plt.text(np.argmax(y), max(y), 'Max')

plt.axvline(mean+stdev, color='blue', linestyle='dashed', linewidth=1)
plt.axvline(mean-stdev, color='blue', linestyle='dashed', linewidth=1)
plt.text(mean+stdev, Lenght[int(mean+stdev)], 'Mean +/- stdev')

plt.axvline(bin_max, color='green', linestyle='dashed', linewidth=1)
plt.text(bin_max, 0.8*max(y), '{0:.1f}-threshold'.format((1-ex_thr)*100))
plt.axvline(bin_min, color='green', linestyle='dashed', linewidth=1)
plt.text(bin_min, 0.8*max(y), '{0:.1f}-threshold'.format(ex_thr*100))
plt.show()

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Mean of distribution = 3.12(1.24)
Total integral : 79896.00
90% integral : 79896.00 at 5
10% integral : 8053.00 at 1
Max of distribution = 22294.00(3.00)


Pour l'instant on décide de ne pas réduire le data set sur la taille des tags.

In [40]:
top = 3
lst = [['premier','deuxieme','troisieme' ], ['premier','deuxieme','troisieme' ], ['premier','deuxieme','troisieme' ]]
df_test = pd.DataFrame({'Col1' : lst})
df_test
count, words = exp.most_common_words(df_test['Col1'], ', ', top)
pd.DataFrame([words, count])

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


0         1          2
0  premier  deuxieme  troisieme
1        3         3          3

Vérification du bon fonctionnement de la fonction précédente.

In [41]:
top = 3
fig = plt.figure(figsize=(10,9))

plt.hist(x=words, weights=count, bins = top)
plt.title('The top {:d} of most frequent words'.format(top))
plt.xticks(rotation=90)
plt.show()

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [42]:
def frequence_words(labels, delimiter):
    words = []
    unique = []
    count = []
    words_list = []
    for lab in labels:
        words_list = pd.Series(lab).unique().tolist()
        unique += exp.get_words(words_list, delimiter)
        
        words += exp.get_words(lab, delimiter)
    counter_w = Counter(words)
    counter_u = Counter(unique)
    words = []
    unique = []
    i = 0
    for word in counter_w:
        words.append(word)
        count.append(counter_w[word])
        unique.append(counter_u[word])
    
    df = pd.DataFrame({'Words' : words, 'Count' : count, 'Documents' : unique}).sort_values(by=['Count'], ascending=False)
    return df

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [43]:
top = 50
df_freq = frequence_words(DataReduced['Body'], ', ')
df_freq

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


Words  Count  Documents
66                   data  69272      21486
142                 value  66049      22111
37                   code  65574      36872
70                  class  65423      20173
2                    file  63943      18838
...                   ...    ...        ...
130512             anular      1          1
130511           sparkjob      1          1
130507         addcookies      1          1
130505  baseapicontroller      1          1
244647        cursedembed      1          1

[244648 rows x 3 columns]

In [55]:
save_df_as_image(df_freq[:5], './Images/Words_freq.png')

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


On fait une fonction qui permet de voir les différents mots du corpus, leur nombre et leur présence dans les documents.

In [34]:
df_freq[df_freq['Documents'] < 2]

Words  Count  Documents
66869                vrtx    102          1
194304             chembl    100          1
122337           datarace     71          1
175933            mahmood     63          1
80981           cutnumber     60          1
...                   ...    ...        ...
130512             anular      1          1
130511           sparkjob      1          1
130507         addcookies      1          1
130505  baseapicontroller      1          1
244647        cursedembed      1          1

[180233 rows x 3 columns]

On regarde les documents présent dans un seul document, l'objectif sera de les enlever pour réduire les features, surtout que ces mots ne permettront pas de définir les sujets.

In [44]:
df_freq.plot(x='Count', y='Documents', kind='scatter')
# plt.yscale('log')
plt.show()

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Canvas).__init__().
__init__() missing 1 required positional argument: 'figure'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Widget, self).__init__(**kwargs)
D:\Anaconda3\lib\site-packages\ipywidgets\widgets\widget.py:412: DeprecationWarning: Passing unrecognized arguments to super(Toolbar).__init__().
__init__() missing 1 required positional argument: 'canvas'
This is deprecated in traitlets 4.2.This error will be raised in a future release of traitlets.
  super(Wi

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [45]:
def repeated_letters(df, feat, repeat, select='keep'):
    matcher = re.compile(r'(.)\1*')
    col = df[feat].values

    new_col = []
    for c in col:
        if select == 'unkeep':
            keep = True
        else :
            keep = False
    #     print(c)
        for match in matcher.finditer(c):
            if len(match.group())>=repeat:
                if select == 'unkeep':
                    keep = False
                else :
                    keep = True
                break
        if keep :
            new_col.append(c)
    return new_col

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [46]:
repeated = repeated_letters(df_freq, 'Words', 3)
len(repeated)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


2059

In [38]:
repeated

['www',
 'xxx',
 'yyyy',
 'xxxx',
 'fff',
 'aaa',
 'bbb',
 'xxxxx',
 'ccc',
 'ffffff',
 'xxxxxx',
 'yyy',
 'ddd',
 'ffff',
 'aaaa',
 'xxxxxxx',
 'eee',
 'mmm',
 'iii',
 'ieee',
 'zzz',
 'adddbcontext',
 'xffff',
 'wwwroot',
 'yyyymmdd',
 'xxxxxxxxxx',
 'processstartinfo',
 'xxxxxxxxx',
 'xxxxxxxx',
 'xxxxxxxxxxxx',
 'readalllines',
 'xffffffff',
 'cccc',
 'zzzz',
 'issuccessstatuscode',
 'bbbb',
 'dddd',
 'xxxxxxxxxxx',
 'adddays',
 'mmmm',
 'hhh',
 'purrr',
 'jjj',
 'addresssanitizer',
 'ttt',
 'adddata',
 'xbffff',
 'ggg',
 'hrrr',
 'ensuresuccessstatuscode',
 'fffffff',
 'aaaaa',
 'sss',
 'aaaaaa',
 'fffff',
 'ppp',
 'vvv',
 'ffffffff',
 'fffffffe',
 'eeee',
 'rrr',
 'eeeeee',
 'bbbbb',
 'fwww',
 'cccccc',
 'lll',
 'dddddd',
 'installlocation',
 'xxxxxxxxxxxxxx',
 'currrequest',
 'kkk',
 'qqq',
 'apppath',
 'getxxxxx',
 'xxxxxxxxxxxxxxxx',
 'fffe',
 'sssz',
 'xxxxxxxxxxxxxxx',
 'zzzzz',
 'oooo',
 'xxxxxxxxxxxxx',
 'fffd',
 'xffffff',
 'naaaad',
 'xxxxxxxxxxxxxxxxxxxxx',
 'aaaaaaa',


Ici on regarde les mots qui on plus de 2 * la même lettre qui se suivent car on voudrait les supprimer en considérant que ces mots n'existe pas. La majorité des mots sont inintéressant mais quelques'un sont importants.

In [47]:
def no_vowel(df, feat, select='keep'):
    col = df[feat].values
    if select == 'unkeep':
        keep = False
    else :
        keep = True
            
    new_col = []
    for c in col:
        s = re.findall(r'\b[^AEIOUY_0-9\W]+\b', c, flags=re.I)
#         print(c)
        if keep:
            for w in s:
                new_col.append(w)
        elif not keep :
            new_col.append(c)
            
    return new_col

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [49]:
novowel = no_vowel(df_freq, 'Words')
novowel

['http',
 'j',
 'src',
 'html',
 'php',
 'td',
 'db',
 't',
 'm',
 'cs',
 'px',
 'www',
 'ssl',
 'xml',
 'df',
 'sdk',
 'npm',
 'sql',
 'jdk',
 'cv',
 'gm',
 'tf',
 'btn',
 'std',
 'dll',
 'pm',
 'th',
 'tcp',
 'cmd',
 'cpp',
 'rb',
 'str',
 'csv',
 'tr',
 'cc',
 'v',
 'ssh',
 'ff',
 'xxx',
 'jdbc',
 'mb',
 'cjs',
 'tl',
 'cd',
 'c',
 'xmlns',
 'png',
 'gcc',
 'tmp',
 'mvc',
 'msvc',
 'txt',
 'br',
 'md',
 'pdf',
 'mm',
 'plt',
 'dd',
 'msg',
 'pc',
 'jwt',
 'fff',
 'fb',
 'jpg',
 'kb',
 'pd',
 'vc',
 'xx',
 'rc',
 'bb',
 'jsx',
 'bf',
 'pcl',
 'p',
 'ng',
 'cf',
 'vm',
 'np',
 'mp',
 'bd',
 'gb',
 'sh',
 'dc',
 'f',
 'xc',
 'sm',
 'mt',
 'npmjs',
 'xsd',
 'smtp',
 'ch',
 'fc',
 'sc',
 'pg',
 'cp',
 'cl',
 'xxxx',
 'fn',
 'svg',
 'sdl',
 'csrf',
 'dp',
 'bc',
 'cb',
 'rw',
 'rt',
 'dl',
 'ctx',
 'l',
 'fd',
 'qt',
 'x',
 'ptr',
 'kt',
 'jvm',
 'sp',
 'w',
 'fp',
 'gz',
 'rm',
 'gmt',
 'st',
 'r',
 'xxxxxx',
 'tk',
 'httpd',
 'vpc',
 'pkg',
 'gh',
 'gd',
 'gc',
 'msb',
 'xhr',
 'xxxxx',

On regardes les mots sans voyelles en considérant qu'il n'existe pas et ne sont pas important. Les mots sans voyelles sont important !

In [48]:
u_doc = df_freq[df_freq['Documents'] < 2].loc[:,'Words'].values.tolist()
len(u_doc)

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


180233

In [49]:
def del_words(row, feat, words, bar=None, lenght=None):
    if lenght is not None:
        progress = row.name / lenght
    else:
        progress = 1
#     print('Flag 1')
    new_list = []
    new_list = [w for w in row[feat] if w not in words]
    row[feat] = new_list
#     print(new_list)
    if bar is not None:
        bar.update_progress(progress)
    return row

D:\Anaconda3\lib\site-packages\ipykernel\ipkernel.py:287: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)


In [44]:
df = DataReduced.copy()
bar = progress_bar(10, 'del_words', 1e-2)
# bar = progress_bar(10, 'treatement', time_lim=1)
bar.set_progress(0)

del_arrow = repeated
DataReduced = df.apply(
    del_words,
    args = ('Body', del_arrow, bar, len(df)),
    axis = 1
)

bar.update_progress(1)
DataReduced.describe()

Progress del_words: [##################################################] 126.00% 0:04:38.001619

Id  PostTypeId  ParentId         CreationDate  Score  ViewCount  \
1   59549292           1       NaN  2020-01-01 00:27:42      0        266   
2   59549299           1       NaN  2020-01-01 00:29:41     -2        477   
4   59549388           1       NaN  2020-01-01 00:58:27      0         80   
5   59549397           1       NaN  2020-01-01 01:01:55     -6         84   
6   59549477           1       NaN  2020-01-01 01:28:58      0        459   
7   59549514           1       NaN  2020-01-01 01:40:05      0       1193   
8   59549593           1       NaN  2020-01-01 02:03:35      2        427   
9   59549661           1       NaN  2020-01-01 02:28:04      1         76   
10  59549750           1       NaN  2020-01-01 02:59:38      0        173   
11  59549824           1       NaN  2020-01-01 03:23:31     -2         74   

                                       Body  OwnerUserId  \
1   [cycle, list, file, array, expressio...   11059320.0   
2   [body, background, color, size, px, ...   12633966.0   
4   [height, row, march, product, jiko, ...   12069171.0   
5   [code, function, number, array, powe...   12433880.0   
6   [language, book, primer, plus, curre...   12352162.0   
7   [error, app, browser, chrome, edge, ...    2538627.0   
8   [tutorial, food, search, app, user, ...    2654750.0   
9   [figure, life, reason, screen, regar...   12572660.0   
10  [answer, post, file, size, image, fi...   12348447.0   
11  [problem, time, linux, root, user, j...    4280836.0   

                                      Title  \
1   [filter, list, file, array, expression]   
2    [text, background, color, text, color]   
4                        [height, row, row]   
5   [program, wont, work, function, segm...   
6     [character, constant, initialization]   
7   [cors, issue, angular, aws, cloudfro...   
8          [ajax, javascript, wamp, server]   
9                        [selector, jquery]   
10             [file, size, image, gallery]   
11          [data, randomaccessfile, linux]   

                                       Tags  AnswerCount  CommentCount  \
1                              [powershell]            2            11   
2                               [html, css]            1            12   
4                               [html, css]            2             6   
5       [c++, function, segmentation-fault]            1             6   
6                 [c, char, int, constants]            2             8   
7   [asp.net-core, amazon-s3, cors, angu...            2            11   
8       [javascript, php, ajax, wampserver]            1            10   
9                [javascript, jquery, html]            2             7   
10                                [android]            5             6   
11  [java, linux, java-io, randomaccessf...            1             8   

    FavoriteCount           ClosedDate  
1             NaN                  NaN  
2             NaN                  NaN  
4             NaN                  NaN  
5             NaN  2020-01-01 01:36:16  
6             NaN                  NaN  
7             0.0                  NaN  
8             NaN                  NaN  
9             NaN                  NaN  
10            NaN                  NaN  
11            NaN  2020-01-01 08:50:42

In [45]:
# bar = progress_bar(10, 'del_words', 1e-2)
bar = progress_bar(10, 'treatement', time_lim=1)
bar.set_progress(0)

del_arrow = u_doc
DataReduced = DataReduced.apply(
    del_words,
    args = ('Body', del_arrow, bar, len(DataReduced)),
    axis = 1
)

bar.update_progress(1)
DataReduced.head(10)

Progress treatement: [----------------------------------------] 0.63% 0:05:40.220253

KeyboardInterrupt: 

In [46]:
ProgressBar().register()
ddata = dd.from_pandas(DataReduced, npartitions=4*multiprocessing.cpu_count())

del_arrow = u_doc
with ProgressBar():
    DataReduced = ddata.map_partitions(
        lambda df: df.apply(
            del_words,
            args=('Body', del_arrow),
            axis = 1
        )
    ).compute(scheduler='processes')
DataReduced.head(5)

[########################################] | 100% Completed |  2hr 34min 14.7s
[########################################] | 100% Completed |  2hr 34min 14.8s


Id  PostTypeId  ParentId         CreationDate  Score  ViewCount  \
1   59549292           1       NaN  2020-01-01 00:27:42      0        266   
2   59549299           1       NaN  2020-01-01 00:29:41     -2        477   
4   59549388           1       NaN  2020-01-01 00:58:27      0         80   
5   59549397           1       NaN  2020-01-01 01:01:55     -6         84   
6   59549477           1       NaN  2020-01-01 01:28:58      0        459   
7   59549514           1       NaN  2020-01-01 01:40:05      0       1193   
8   59549593           1       NaN  2020-01-01 02:03:35      2        427   
9   59549661           1       NaN  2020-01-01 02:28:04      1         76   
10  59549750           1       NaN  2020-01-01 02:59:38      0        173   
11  59549824           1       NaN  2020-01-01 03:23:31     -2         74   

                                       Body  OwnerUserId  \
1   [cycle, list, file, array, expressio...   11059320.0   
2   [body, background, color, size, px, ...   12633966.0   
4   [height, row, march, product, eco, r...   12069171.0   
5   [code, function, number, array, powe...   12433880.0   
6   [language, book, primer, plus, curre...   12352162.0   
7   [error, app, browser, chrome, edge, ...    2538627.0   
8   [tutorial, food, search, app, user, ...    2654750.0   
9   [figure, life, reason, screen, regar...   12572660.0   
10  [answer, post, file, size, image, fi...   12348447.0   
11  [problem, time, linux, root, user, j...    4280836.0   

                                      Title  \
1   [filter, list, file, array, expression]   
2    [text, background, color, text, color]   
4                        [height, row, row]   
5   [program, wont, work, function, segm...   
6     [character, constant, initialization]   
7   [cors, issue, angular, aws, cloudfro...   
8          [ajax, javascript, wamp, server]   
9                        [selector, jquery]   
10             [file, size, image, gallery]   
11          [data, randomaccessfile, linux]   

                                       Tags  AnswerCount  CommentCount  \
1                              [powershell]            2            11   
2                               [html, css]            1            12   
4                               [html, css]            2             6   
5       [c++, function, segmentation-fault]            1             6   
6                 [c, char, int, constants]            2             8   
7   [asp.net-core, amazon-s3, cors, angu...            2            11   
8       [javascript, php, ajax, wampserver]            1            10   
9                [javascript, jquery, html]            2             7   
10                                [android]            5             6   
11  [java, linux, java-io, randomaccessf...            1             8   

    FavoriteCount           ClosedDate  
1             NaN                  NaN  
2             NaN                  NaN  
4             NaN                  NaN  
5             NaN  2020-01-01 01:36:16  
6             NaN                  NaN  
7             0.0                  NaN  
8             NaN                  NaN  
9             NaN                  NaN  
10            NaN                  NaN  
11            NaN  2020-01-01 08:50:42

In [48]:
DataReduced.describe()

Id  PostTypeId  ParentId         Score      ViewCount  \
count  7.989600e+04     79896.0       0.0  79896.000000   79896.000000   
mean   6.238600e+07         1.0       NaN      0.806198     595.719360   
std    1.753194e+06         0.0       NaN      4.325216    3194.528955   
min    5.954929e+07         1.0       NaN    -12.000000      51.000000   
25%    6.078524e+07         1.0       NaN      0.000000      84.000000   
50%    6.237202e+07         1.0       NaN      0.000000     166.000000   
75%    6.385348e+07         1.0       NaN      1.000000     437.000000   
max    6.555971e+07         1.0       NaN    609.000000  339670.000000   

        OwnerUserId   AnswerCount  CommentCount  FavoriteCount  
count  7.790200e+04  79896.000000  79896.000000   13788.000000  
mean   8.801545e+06      1.533293      8.356639       1.195677  
std    4.582230e+06      0.944624      2.924564       2.157538  
min    9.100000e+01      1.000000      6.000000       0.000000  
25%    4.763651e+06      1.000000      6.000000       1.000000  
50%    1.008557e+07      1.000000      7.000000       1.000000  
75%    1.288766e+07      2.000000      9.000000       1.000000  
max    1.571046e+07     51.000000     74.000000     179.000000

Ici on supprime les mots contenue dans une liste.
On se retrouve avec 79896 individues et 15 varriables

In [3]:
FILE_Model = "./Data/DataCleaned_v1.csv"
# DataReduced.to_csv(FILE_Model, index=False, doublequote=False)

DataReduced = pd.read_csv(FILE_Model, encoding="utf-8", low_memory=False, doublequote=False, error_bad_lines=False)
DataReduced['Body'] = DataReduced['Body'].astype('str')
DataReduced['Body'] = DataReduced.Body.apply(
    lambda x: 
    x.replace('\'', '')
    .replace('[', '')
    .replace(']', '')
).apply(
    lambda x: x[:].split(', ')
)
DataReduced['Title'] = DataReduced.Title.apply(
    lambda x: 
    x.replace('\'', '')
    .replace('[', '')
    .replace(']', '')
).apply(
    lambda x: x[:].split(', ')
)
DataReduced['Tags'] = DataReduced.Tags.apply(
    lambda x: 
    x.replace('\'', '')
    .replace('[', '')
    .replace(']', '')
).apply(
    lambda x: x[:].split(', ')
)

DataReduced

Id  PostTypeId  ParentId         CreationDate  Score  ViewCount  \
0      59549292           1       NaN  2020-01-01 00:27:42      0        266   
1      59549299           1       NaN  2020-01-01 00:29:41     -2        477   
2      59549388           1       NaN  2020-01-01 00:58:27      0         80   
3      59549397           1       NaN  2020-01-01 01:01:55     -6         84   
4      59549477           1       NaN  2020-01-01 01:28:58      0        459   
...         ...         ...       ...                  ...    ...        ...   
79891  65514630           1       NaN  2020-12-30 23:02:42     -2         96   
79892  65514632           1       NaN  2020-12-30 23:02:54     -2         57   
79893  65514712           1       NaN  2020-12-30 23:13:53      0        265   
79894  65514890           1       NaN  2020-12-30 23:37:04      1        225   
79895  65515004           1       NaN  2020-12-30 23:53:24      0        102   

                                          Body  OwnerUserId  \
0      [cycle, list, file, array, expressio...   11059320.0   
1      [body, background, color, size, px, ...   12633966.0   
2      [height, row, march, product, eco, r...   12069171.0   
3      [code, function, number, array, powe...   12433880.0   
4      [language, book, primer, plus, curre...   12352162.0   
...                                        ...          ...   
79891  [problem, piece, chessboard, king, w...   14687335.0   
79892  [middle, calendar, javascript, date,...          NaN   
79893  [join, table, problem, table, table,...   15040818.0   
79894  [version, function, isalpha, work, l...       4668.0   
79895  [image, command, discord, j, bot, er...   14722081.0   

                                         Title  \
0      [filter, list, file, array, expression]   
1       [text, background, color, text, color]   
2                           [height, row, row]   
3      [program, wont, work, function, segm...   
4        [character, constant, initialization]   
...                                        ...   
79891                   [program, queen, king]   
79892                   [calendar, javascript]   
79893                   [jpa, jpql, statement]   
79894  [glibc, isalpha, function, u, utf, l...   
79895  [problem, reddit, command, discord, ...   

                                      Tags  AnswerCount  CommentCount  \
0                             [powershell]            2            11   
1                              [html, css]            1            12   
2                              [html, css]            2             6   
3      [c++, function, segmentation-fault]            1             6   
4                [c, char, int, constants]            2             8   
...                                    ...          ...           ...   
79891                                  [c]            1            10   
79892                         [javascript]            2             6   
79893  [java, mysql, hibernate, jpa, jpql]            2             7   
79894              [c, locale, glibc, utf]            1             8   
79895                         [discord.js]            1             6   

       FavoriteCount           ClosedDate  
0                NaN                  NaN  
1                NaN                  NaN  
2                NaN                  NaN  
3                NaN  2020-01-01 01:36:16  
4                NaN                  NaN  
...              ...                  ...  
79891            NaN                  NaN  
79892            NaN                  NaN  
79893            NaN                  NaN  
79894            NaN                  NaN  
79895            NaN                  NaN  

[79896 rows x 14 columns]

### 2.B) Analyse bivariée 

## 3) Vectorization & Visualisation

In [4]:
def select_tags(row, words):
    if any( item in words for item in row['Tags'] ):
        return row
    else :
        row['Tags'] = np.nan
    return row

In [5]:
df = DataReduced.copy()

top = 369
count, words = exp.most_common_words(DataReduced['Tags'], ', ', top)
pd.DataFrame([words, count])

# DataTagged = df.apply(select_tags, args=([words]), axis = 1)

ProgressBar().register()
ddata = dd.from_pandas(df, npartitions=4*multiprocessing.cpu_count())

with ProgressBar():
    DataTagged = ddata.map_partitions(
        lambda df: df.apply(
            select_tags,
            args=([words]),
            axis = 1
        )
    ).compute(scheduler='processes')

DataTagged = DataTagged.dropna(subset=['Tags'])
# DataTagged.describe(include = 'all')
DataTagged

[########################################] | 100% Completed |  8.3s
[########################################] | 100% Completed |  8.4s


Id  PostTypeId  ParentId         CreationDate  Score  ViewCount  \
0      59549292           1       NaN  2020-01-01 00:27:42      0        266   
1      59549299           1       NaN  2020-01-01 00:29:41     -2        477   
2      59549388           1       NaN  2020-01-01 00:58:27      0         80   
3      59549397           1       NaN  2020-01-01 01:01:55     -6         84   
4      59549477           1       NaN  2020-01-01 01:28:58      0        459   
...         ...         ...       ...                  ...    ...        ...   
79891  65514630           1       NaN  2020-12-30 23:02:42     -2         96   
79892  65514632           1       NaN  2020-12-30 23:02:54     -2         57   
79893  65514712           1       NaN  2020-12-30 23:13:53      0        265   
79894  65514890           1       NaN  2020-12-30 23:37:04      1        225   
79895  65515004           1       NaN  2020-12-30 23:53:24      0        102   

                                          Body  OwnerUserId  \
0      [cycle, list, file, array, expressio...   11059320.0   
1      [body, background, color, size, px, ...   12633966.0   
2      [height, row, march, product, eco, r...   12069171.0   
3      [code, function, number, array, powe...   12433880.0   
4      [language, book, primer, plus, curre...   12352162.0   
...                                        ...          ...   
79891  [problem, piece, chessboard, king, w...   14687335.0   
79892  [middle, calendar, javascript, date,...          NaN   
79893  [join, table, problem, table, table,...   15040818.0   
79894  [version, function, isalpha, work, l...       4668.0   
79895  [image, command, discord, j, bot, er...   14722081.0   

                                         Title  \
0      [filter, list, file, array, expression]   
1       [text, background, color, text, color]   
2                           [height, row, row]   
3      [program, wont, work, function, segm...   
4        [character, constant, initialization]   
...                                        ...   
79891                   [program, queen, king]   
79892                   [calendar, javascript]   
79893                   [jpa, jpql, statement]   
79894  [glibc, isalpha, function, u, utf, l...   
79895  [problem, reddit, command, discord, ...   

                                      Tags  AnswerCount  CommentCount  \
0                             [powershell]            2            11   
1                              [html, css]            1            12   
2                              [html, css]            2             6   
3      [c++, function, segmentation-fault]            1             6   
4                [c, char, int, constants]            2             8   
...                                    ...          ...           ...   
79891                                  [c]            1            10   
79892                         [javascript]            2             6   
79893  [java, mysql, hibernate, jpa, jpql]            2             7   
79894              [c, locale, glibc, utf]            1             8   
79895                         [discord.js]            1             6   

       FavoriteCount           ClosedDate  
0                NaN                  NaN  
1                NaN                  NaN  
2                NaN                  NaN  
3                NaN  2020-01-01 01:36:16  
4                NaN                  NaN  
...              ...                  ...  
79891            NaN                  NaN  
79892            NaN                  NaN  
79893            NaN                  NaN  
79894            NaN                  NaN  
79895            NaN                  NaN  

[77782 rows x 14 columns]

In [15]:
words

['python',
 'javascript',
 'c++',
 'c#',
 'java',
 'c',
 'php',
 'html',
 'reactjs',
 'sql',
 'arrays',
 'python-3.x',
 'node.js',
 'android',
 'css',
 'mysql',
 'angular',
 'laravel',
 'json',
 'r',
 'sql-server',
 'jquery',
 'swift',
 'pandas',
 'typescript',
 'excel',
 'vba',
 'ios',
 'regex',
 'algorithm',
 'string',
 'bash',
 'flutter',
 '.net',
 'django',
 'linux',
 'asp.net-core',
 'docker',
 'list',
 'spring-boot',
 'vue.js',
 'amazon-web-services',
 'firebase',
 'numpy',
 'pointers',
 'multithreading',
 'postgresql',
 '.net-core',
 'function',
 'spring',
 'dataframe',
 'windows',
 'react-native',
 'mongodb',
 'azure',
 'loops',
 'ajax',
 'performance',
 'google-apps-script',
 'kotlin',
 'oracle',
 'powershell',
 'asp.net',
 'visual-studio',
 'git',
 'dart',
 'go',
 'csv',
 'for-loop',
 'dictionary',
 'linq',
 'class',
 'c++11',
 'shell',
 'kubernetes',
 'database',
 'express',
 'async-await',
 'sorting',
 'tkinter',
 'assembly',
 'file',
 'api',
 'google-sheets',
 'selenium',


In [6]:
df = DataTagged.copy()
corpora = df['Title'] + df['Body']

# Create a dictionary representation of the documents.
dictionary = Dictionary(corpora)

# Filter out words that occur less than 20 documents, or more than 50% of the documents.
dictionary.filter_extremes(no_below=20, no_above=0.5)
print('Data prepared')

corpus = [dictionary.doc2bow(doc) for doc in corpora]

print('Number of unique tokens: %d' % len(dictionary))
print('Number of documents: %d' % len(corpus))

Data prepared
Number of unique tokens: 8660
Number of documents: 77782


In [260]:
corpus

[[(0, 9),
  (1, 4),
  (2, 1),
  (3, 1),
  (4, 1),
  (5, 2),
  (6, 11),
  (7, 5),
  (8, 2),
  (9, 2),
  (10, 1),
  (11, 6),
  (12, 1),
  (13, 2),
  (14, 1),
  (15, 1),
  (16, 2),
  (17, 1),
  (18, 18),
  (19, 1),
  (20, 5),
  (21, 3),
  (22, 1),
  (23, 3),
  (24, 1)],
 [(19, 1),
  (25, 1),
  (26, 3),
  (27, 3),
  (28, 1),
  (29, 6),
  (30, 2),
  (31, 1),
  (32, 2),
  (33, 2),
  (34, 1),
  (35, 3),
  (36, 1),
  (37, 1),
  (38, 1),
  (39, 1),
  (40, 1),
  (41, 1),
  (42, 1),
  (43, 1),
  (44, 2),
  (45, 1),
  (46, 7),
  (47, 2),
  (48, 1)],
 [(17, 1),
  (26, 3),
  (28, 3),
  (29, 3),
  (32, 2),
  (35, 1),
  (40, 6),
  (43, 2),
  (44, 1),
  (47, 1),
  (49, 1),
  (50, 2),
  (51, 1),
  (52, 2),
  (53, 1),
  (54, 1),
  (55, 2),
  (56, 1),
  (57, 1),
  (58, 1),
  (59, 2),
  (60, 1),
  (61, 5),
  (62, 2),
  (63, 1),
  (64, 1),
  (65, 1),
  (66, 1),
  (67, 1),
  (68, 1),
  (69, 3),
  (70, 1),
  (71, 1),
  (72, 1),
  (73, 1),
  (74, 1),
  (75, 1),
  (76, 3),
  (77, 2),
  (78, 1),
  (79, 2),
  (80

### 3.A) Text Fréquency - Inverse Document Frequency (tf-idf)

On peut transformer un texte en ses features soit :
- En utilisant une représentation de comptage creuse - fréquence d’apparition du mot dans un document, ou vecteur tf-idf d’un document, etc.
- En utilisant une représentation type word2vec dense - dans laquelle le mot possède une représentation dans un espace qui le positionne en fonction des mots adjacents

Ici on veut carractériser les textes par un tags on veut donc rechercher des mots-clef. A cette fin une représentation de comptage creuse semble plus pertinente.

In [14]:
def parallelize_dataframe(df, func, options=None, num_partitions=None):
    print('debug par_df 1: ', options, num_partitions)
    num_cores = multiprocessing.cpu_count()
    
    if num_partitions is None:
        a = np.array_split(df, num_cores)
    else :
        a = np.array_split(df, num_partitions)
    print('debug par_df 2')

    rc = ipp.Cluster(n=4).start_and_connect_sync()
    dview=rc[:]
    
    if options is None:
        print('debug par_df 3.1')
        result = dview.map_sync(func, df)
    else :
        print('debug par_df 3.2')
        result = dview.map_sync(func, df, options)
        
    print('debug par_df 4')
    return result

def f_return(text):
    return text

def TFidF(corpora, rejected=None):
    print('debug TFidF 1')
    vectorizer = skl.feature_extraction.text.TfidfVectorizer(
        token_pattern=None,
        stop_words = rejected,
        analyzer = 'word',
        preprocessor = f_return,
        tokenizer = f_return
        )
    print('debug TFidF 2')
    result = vectorizer.fit_transform(corpora)
    print('debug TFidF 3')
    features = vectorizer.get_feature_names()
    print('debug TFidF 4')
    return features, result

In [16]:
def test_parrallelisation(labels, feat):
#     bar = progress_bar(40, 'test', time_lim=1)
#     lenght = len(df)
#     for index, lab in enumerate(labels):
#         progress = index / df
#         bar.update_progress(progress)
    print(df[feat])
    return

In [ ]:
df = DataModel.copy()
t0=time.time()
parallelize_dataframe(df, test_parrallelisation, 'Tags')
print (time.time() - t0)

debug par_df 1:  Tags None
debug par_df 2
debug par_df 3.2


In [15]:
# rejected = u_doc
df = DataTagged.copy()
corpora = df['Title'] + df['Body']

 # print('Corpora :', corpus)
 # print(len(corpora),'\n')

vectorizer = skl.feature_extraction.text.TfidfVectorizer(
    token_pattern=None,
#     stop_words = rejected,
    analyzer = 'word',
    preprocessor = f_return,
    tokenizer = f_return
    )

t0=time.time()
X = vectorizer.fit_transform(corpora)
features = vectorizer.get_feature_names()
print ('Fitting Time : {} seconds'.format(time.time() - t0) )

 # print('TF-iDF : ', vectorizer.get_feature_names())
DataBow = pd.DataFrame(X.todense(), columns=features)
DataBow.head()

Fitting Time : 3.026285409927368 seconds


a   aa  aab  aabaa  aabb  aabbc  \
0  0.0  0.0  0.0    0.0   0.0    0.0   
1  0.0  0.0  0.0    0.0   0.0    0.0   
2  0.0  0.0  0.0    0.0   0.0    0.0   
3  0.0  0.0  0.0    0.0   0.0    0.0   
4  0.0  0.0  0.0    0.0   0.0    0.0   

   aabbccddeeffgghhiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz  aabc  aabccdd  aac  \
0                                      0.0                0.0      0.0  0.0   
1                                      0.0                0.0      0.0  0.0   
2                                      0.0                0.0      0.0  0.0   
3                                      0.0                0.0      0.0  0.0   
4                                      0.0                0.0      0.0  0.0   

   aacb  aacd  aacute  aad  aadapter  aadb  aadc  aadhaar  aadhar  aadharno  \
0   0.0   0.0     0.0  0.0       0.0   0.0   0.0      0.0     0.0       0.0   
1   0.0   0.0     0.0  0.0       0.0   0.0   0.0      0.0     0.0       0.0   
2   0.0   0.0     0.0  0.0       0.0   0.0   0.0      0.0     0.0       0.0   
3   0.0   0.0     0.0  0.0       0.0   0.0   0.0      0.0     0.0       0.0   
4   0.0   0.0     0.0  0.0       0.0   0.0   0.0      0.0     0.0       0.0   

   aadsts  aae  aaeb  aaf  aafcd  aafd  aafeb  aaff  aag  aal  aam  aan  \
0     0.0  0.0   0.0  0.0    0.0   0.0    0.0   0.0  0.0  0.0  0.0  0.0   
1     0.0  0.0   0.0  0.0    0.0   0.0    0.0   0.0  0.0  0.0  0.0  0.0   
2     0.0  0.0   0.0  0.0    0.0   0.0    0.0   0.0  0.0  0.0  0.0  0.0   
3     0.0  0.0   0.0  0.0    0.0   0.0    0.0   0.0  0.0  0.0  0.0  0.0   
4     0.0  0.0   0.0  0.0    0.0   0.0    0.0   0.0  0.0  0.0  0.0  0.0   

   aantal  aap  aapl  aapt  aar  aarch  aardvark  aaron  aasf  aasm  aat  \
0     0.0  0.0   0.0   0.0  0.0    0.0       0.0    0.0   0.0   0.0  0.0   
1     0.0  0.0   0.0   0.0  0.0    0.0       0.0    0.0   0.0   0.0  0.0   
2     0.0  0.0   0.0   0.0  0.0    0.0       0.0    0.0   0.0   0.0  0.0   
3     0.0  0.0   0.0   0.0  0.0    0.0       0.0    0.0   0.0   0.0  0.0   
4     0.0  0.0   0.0   0.0  0.0    0.0       0.0    0.0   0.0   0.0  0.0   

   aatg  aatrox  aav  aaw  aax  aaz  aazgjwfdmvna   ab  aba  abaa  abab  \
0   0.0     0.0  0.0  0.0  0.0  0.0           0.0  0.0  0.0   0.0   0.0   
1   0.0     0.0  0.0  0.0  0.0  0.0           0.0  0.0  0.0   0.0   0.0   
2   0.0     0.0  0.0  0.0  0.0  0.0           0.0  0.0  0.0   0.0   0.0   
3   0.0     0.0  0.0  0.0  0.0  0.0           0.0  0.0  0.0   0.0   0.0   
4   0.0     0.0  0.0  0.0  0.0  0.0           0.0  0.0  0.0   0.0   0.0   

   ababa  abac  abandon  abandoned  abap  abaqus  abarth  abb  abba  abbc  \
0    0.0   0.0      0.0        0.0   0.0     0.0     0.0  0.0   0.0   0.0   
1    0.0   0.0      0.0        0.0   0.0     0.0     0.0  0.0   0.0   0.0   
2    0.0   0.0      0.0        0.0   0.0     0.0     0.0  0.0   0.0   0.0   
3    0.0   0.0      0.0        0.0   0.0     0.0     0.0  0.0   0.0   0.0   
4    0.0   0.0      0.0        0.0   0.0     0.0     0.0  0.0   0.0   0.0   

   abbey  abbr  abbrev  abbreviated  abbreviation  abby  abc  abcabc  \
0    0.0   0.0     0.0          0.0           0.0   0.0  0.0     0.0   
1    0.0   0.0     0.0          0.0           0.0   0.0  0.0     0.0   
2    0.0   0.0     0.0          0.0           0.0   0.0  0.0     0.0   
3    0.0   0.0     0.0          0.0           0.0   0.0  0.0     0.0   
4    0.0   0.0     0.0          0.0           0.0   0.0  0.0     0.0   

   abcabcabc  abcaccounting  abcb  abcc  abcd  abcde  abcdeab  abcdef  \
0        0.0            0.0   0.0   0.0   0.0    0.0      0.0     0.0   
1        0.0            0.0   0.0   0.0   0.0    0.0      0.0     0.0   
2        0.0            0.0   0.0   0.0   0.0    0.0      0.0     0.0   
3        0.0            0.0   0.0   0.0   0.0    0.0      0.0     0.0   
4        0.0            0.0   0.0   0.0   0.0    0.0      0.0     0.0   

   abcdefabcdef  abcdefg  abcdefgh  abcdefghijk  abcdefghijklmnopqrstuvwxyz  \
0           0.0      0.0       0.0       

In [18]:
df_freq[df_freq['Words'] == 'abcdefghijklambdaisawesome']

NameError: name 'df_freq' is not defined

In [150]:
feat = 'Body'
lookedfor = [['abcdefghijklambdaisawesome']]
    
test = pd.DataFrame(DataModel[feat].apply(check_words_list, args=(lookedfor)))
test = test[test.astype(str)[feat] != '[]']
test

Body
48955  [abcdefghijklambdaisawesome]

In [151]:
DataRaw.loc[48955, 'Body']

'<p>I\'m trying to invoke my lambda using aws cli:</p>\n\n<pre><code>$ aws lambda invoke \\\n    --function-name soc-update-dynamodb-java \\\n    --invocation-type Event \\\n    --payload file://invoke-payload.json \\\n   response.json\n</code></pre>\n\n<p>However, I\'m getting this message:</p>\n\n<blockquote>\n  <p>An error occurred (InvalidRequestContentException) when calling the Invoke operation: Could not parse request body into json: Invalid UTF-8 middle byte 0x28\n   at [Source: (byte[])"E�(�����U�슉���ޞԨ��k.....</p>\n</blockquote>\n\n<p><code>payload.json</code> content is a s3 event-like json:</p>\n\n<pre><code>{\n"Records": [\n  {\n    "eventVersion": "2.0",\n    "eventSource": "aws:s3",\n    "awsRegion": "eu-central-1",\n    "eventTime": "1970-01-01T00:00:00.000Z",\n    "eventName": "ObjectCreated:Put",\n    "userIdentity": {\n      "principalId": "EXAMPLE"\n    },\n    "requestParameters": {\n      "sourceIPAddress": "127.0.0.1"\n    },\n    "responseElements": {\n      "x-

In [19]:
col = DataBow.columns
x = []
for c in col:
#     print(c)
    x.append(len(c))

fig = plt.figure(figsize=(10,9))
plt.hist(x, bins = 186, rwidth=0.8)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [16]:
# DataBow.select_dtypes(exclude=['datetime64'])

#### Gensim library

In [297]:
tfidf = TfidfModel(corpus, normalize=True)
corpus_tfidf = tfidf[corpus]
corpus_tfidf

### 3.B) Word2vec

In [268]:
from gensim.test.utils import common_texts
from gensim.models.doc2vec import Doc2Vec, TaggedDocument
from gensim.models import Word2Vec

In [273]:
print(common_texts)

[['human', 'interface', 'computer'], ['survey', 'user', 'computer', 'system', 'response', 'time'], ['eps', 'user', 'interface', 'system'], ['system', 'human', 'system', 'eps'], ['user', 'response', 'time'], ['trees'], ['graph', 'trees'], ['graph', 'minors', 'trees'], ['graph', 'minors', 'survey']]


In [288]:
model = Word2Vec(sentences=common_texts, vector_size=100, window=5, min_count=1, workers=4)
vector = model.wv['computer']  # get numpy vector of a word
sims = model.wv.most_similar('computer', topn=10)  # get other similar words
corpus_w2v = model.wv
corpus_w2v

### 3.C) Doc2vec

In [289]:
documents = [TaggedDocument(doc, [i]) for i, doc in enumerate(common_texts)]
model = Doc2Vec(documents, vector_size=5, window=2, min_count=1, workers=4)
corpus_d2v = model.wv
corpus_d2v

### 3.D) t-SNE

In [14]:
n_view = 2
n_feat = 2559

data_pca = DataBow.copy()

Values = data_pca.values
features = data_pca.columns

pca = decomposition.PCA(n_components=n_view).fit(Values)
X_PCA = pca.transform(Values)

plt.ioff()
fig3D = plt.figure(figsize=(7,6))
if n_view == 3:
    ax = fig3D.gca(projection='3d')
    ax.scatter(X_PCA[:,0], X_PCA[:,1], X_PCA[:,2])
    ax.set_xlabel('F0', fontsize=10)
    ax.set_ylabel('F1', fontsize=10)
    ax.set_zlabel('F2', fontsize=10)
elif n_view == 2:
    ax = fig3D.gca()
    ax.scatter(X_PCA[:,0], X_PCA[:,1])
    ax.set_xlabel('F0', fontsize=10)
    ax.set_ylabel('F1', fontsize=10)
else :
    print('No Draw')

plt.show(block=False)

data_pca.describe()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

F0            F1            F2            F3            F4  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean   6.536265e-18 -3.316791e-18 -5.289887e-18  3.166911e-18  7.755667e-18   
std    8.247344e-02  7.766118e-02  7.553115e-02  7.273041e-02  7.115833e-02   
min   -2.882734e-01 -4.947918e-01 -5.235537e-01 -2.335974e-01 -2.869653e-01   
25%   -2.552564e-02 -2.630019e-02 -1.030797e-02 -3.327501e-02 -2.369672e-02   
50%   -1.100203e-02 -1.706697e-02  8.277864e-04 -2.384730e-02  1.578791e-03   
75%   -2.456715e-03  9.445649e-03  9.338645e-03  1.538038e-02  9.815745e-03   
max    8.249993e-01  6.889064e-01  7.514783e-01  6.938580e-01  8.004692e-01   

                 F5            F6            F7            F8            F9  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean   3.792106e-18  2.242130e-18 -3.745919e-20 -1.176576e-18  2.920580e-18   
std    6.949417e-02  6.518382e-02  6.467758e-02  6.395072e-02  6.316619e-02   
min   -1.837296e-01 -3.663841e-01 -3.377776e-01 -2.171369e-01 -5.832776e-01   
25%   -3.181349e-02 -1.350312e-02 -1.600210e-02 -2.535217e-02 -1.493886e-02   
50%   -2.098933e-02 -4.881130e-03 -7.788217e-04 -1.365864e-02 -6.328417e-03   
75%    1.561116e-03  1.218774e-02  7.468392e-03  5.901891e-04  1.200912e-02   
max    5.613672e-01  5.313193e-01  7.447356e-01  5.154140e-01  6.350879e-01   

                F10           F11           F12           F13           F14  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean   1.332528e-18  5.604718e-18  2.113761e-18  1.782970e-18 -2.956749e-18   
std    6.252645e-02  6.195337e-02  6.090779e-02  6.001664e-02  5.912685e-02   
min   -4.637372e-01 -3.926553e-01 -3.833084e-01 -2.653040e-01 -3.815491e-01   
25%   -1.264967e-02 -1.676239e-02 -2.431268e-02 -2.013374e-02 -8.956174e-03   
50%   -2.689455e-03  4.195088e-03 -8.500237e-03 -3.632725e-03  5.490919e-03   
75%    1.253367e-02  1.787644e-02  1.317129e-02  8.008612e-03  1.799280e-02   
max    6.264557e-01  5.622142e-01  5.665211e-01  7.123977e-01  5.231237e-01   

                F15           F16           F17           F18           F19  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean  -1.437110e-18 -4.358666e-18  1.360630e-18 -1.380666e-18 -5.967449e-20   
std    5.832101e-02  5.805403e-02  5.712350e-02  5.675096e-02  5.631759e-02   
min   -3.265149e-01 -3.910992e-01 -4.576652e-01 -3.042890e-01 -1.659798e-01   
25%   -1.390563e-02 -1.944280e-02 -1.652468e-02 -1.151709e-02 -2.397508e-02   
50%   -1.535175e-03 -9.684547e-03 -5.541697e-03  4.042046e-03 -1.114364e-02   
75%    1.013021e-02  1.084996e-02  8.149377e-03  1.354661e-02  7.136354e-03   
max    5.135176e-01  4.429356e-01  4.595229e-01  6.738264e-01  4.836002e-01   

                F20           F21           F22           F23           F24  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean  -3.423236e-18  1.925717e-18 -9.242249e-18  3.051552e-18 -2.287753e-18   
std    5.585005e-02  5.530495e-02  5.508697e-02  5.432594e-02  5.415820e-02   
min   -4.032424e-01 -1.731838e-01 -4.566347e-01 -3.002411e-01 -3.956914e-01   
25%   -1.419567e-02 -2.188374e-02 -1.155139e-02 -1.935511e-02 -1.366500e-02   
50%    1.998271e-03 -9.838871e-03 -6.955264e-04 -7.388866e-03 -5.124167e-03   
75%    1.426935e-02  7.998446e-03  1.179631e-02  1.322925e-02  8.769926e-03   
max    5.344990e-01  5.931937e-01  6.530113e-01  4.421357e-01  6.551514e-01   

                F25           F26           F27           F28           F29  \
count  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04  1.000000e+04   
mean   3.472396e-18 -3.072304e-18  2.138610e-18 -3.193366e-18  5.373154e-18   
std    5.291663e-02  5.189952e-02  5.165788e-02  5.130848e-02  5.100845e-02   
min   -2.676905e-01 -3.401240e-01 -3.952522e-01 -4.056710e-01 -3.511826e-01   
25%   -2.230532e-02 -1.334345e-02 -1.740762e-02 -1.382529e-02 

2566 features selected

## 4) Modèles non-supervisé

On veut ici déterminer les différents sujets du corpus. Pour chaque document on veut déterminer les sujets abordés.

### 4.A) Latent Dirichlet allocation (LDA)
C’est une méthode non-supervisée générative qui se base sur les hypothèses suivantes :

- Chaque document du corpus est un ensemble de mots sans ordre (bag-of-words) ;
- Chaque document m aborde un certain nombre de thèmes dans différentes proportions qui lui sont propres p(θm)
- Chaque mot possède une distribution associée à chaque thème p(ϕk). On peut ainsi représenter chaque thème par une probabilité sur chaque mot.
- zn représente le thème du mot wn

Puisque l'on a accès uniquement aux documents, on doit déterminer quels sont les thèmes, les distributions de chaque mot sur les thèmes, la fréquence d’apparition de chaque thème sur le corpus. <br>

A titre d’exemple, voici une liste des hypothèses supplémentaires qui mènent à une modélisation plus riche :

- La distribution des mots sur les thèmes évoluent avec le temps. Ce qui signifie qu’il faut créer une séquence de distribution pour chaque thème qui permet de modéliser l’évolution du thème dans le temps.
- Certains thèmes sont plus proches que d’autres. L’hypothèse d’utiliser la distribution de Dirichlet considère que les différents thèmes sont complètement indépendants alors qu’en réalité certains thèmes ont en général plus de chances d’apparaître ensemble.

#### Gensim library

In [8]:
model_results = {
    'Validation_Set': [],
    'Topics': [],
    'Alpha': [],
    'Eta': [],
    'Coherence': []
}

# Set training parameters.
# num_topics = 369
num_topics = 5
chunksize = 2000
passes = 20
iterations = 400
eval_every = None  # Don't evaluate model perplexity, takes too much time.

# Make a index to word dictionary.
temp = dictionary[0]  # This is only to "load" the dictionary.
id2word = dictionary.id2token

t0=time.time()

for num_topics in range(10,370,10):
    print('Nombre de sujets : {}'.format(num_topics))
    t1 = time.time()
    try:
        model = LdaMulticore(
            random_state=100,
            corpus = corpus,
            id2word = id2word,
            chunksize = chunksize,
        #     alpha = 'auto',
            eta = 'auto',
            iterations = iterations,
            num_topics = num_topics,
            passes = passes,
            eval_every = eval_every
        )
        top_topics = model.top_topics(corpus)
        avg_topic_coherence = sum([t[1] for t in top_topics]) / num_topics
        print('Average topic coherence: %.4f.' % avg_topic_coherence)

        coherence_model_lda = CoherenceModel(
            model = model, 
            texts = corpora, 
            dictionary = dictionary,
            coherence = 'c_v'
        )
        coherence_lda = coherence_model_lda.get_coherence()
        print('Coherence Score: ', coherence_lda)

        model_results['Validation_Set'].append('No Title')
        model_results['Topics'].append(num_topics)
        model_results['Alpha'].append('default')
        model_results['Eta'].append('auto')
        model_results['Coherence'].append(coherence_lda)

        print('Processing Time : {} seconds'.format(time.time() - t1) )
        print('\n')
        
    except :
        print('Problem pour {} sujets '.format(num_topics))
        print('Processing Time : {} seconds'.format(time.time() - t1) )
        print('\n')
    
print('Over all Time : {} seconds'.format(time.time() - t0) )

Nombre de sujets : 10
Average topic coherence: -2.0704.
Coherence Score:  0.5185010429178644
Processing Time : 322.6317141056061 seconds


Nombre de sujets : 20
Average topic coherence: -2.3772.
Coherence Score:  0.521638343134403
Processing Time : 339.5404922962189 seconds


Nombre de sujets : 30
Average topic coherence: -2.5804.
Coherence Score:  0.5198390146136067
Processing Time : 355.1268241405487 seconds


Nombre de sujets : 40
Average topic coherence: -2.9681.
Coherence Score:  0.5211475637925648
Processing Time : 369.91907596588135 seconds


Nombre de sujets : 50
Average topic coherence: -3.1977.
Coherence Score:  0.5241965121637785
Processing Time : 367.232524394989 seconds


Nombre de sujets : 60
Average topic coherence: -3.5524.
Coherence Score:  0.5131414243219301
Processing Time : 378.5189116001129 seconds


Nombre de sujets : 70
Average topic coherence: -3.7023.
Coherence Score:  0.5176110981693821
Processing Time : 428.8258202075958 seconds


Nombre de sujets : 80
Averag

In [10]:
plt.plot(model_results['Topics'], model_results['Coherence'], '-o', label = 'Eta')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

Ici le nombre optimal de sujets est 50.

In [251]:
model_results = {
    'Validation_Set': [],
    'Topics': [],
    'Alpha': [],
    'Eta': [],
    'Coherence': []
}

# Set training parameters.
# num_topics = 369
num_topics = 50
chunksize = 2000
passes = 20
iterations = 400
eval_every = None  # Don't evaluate model perplexity, takes too much time.

# Make a index to word dictionary.
temp = dictionary[0]  # This is only to "load" the dictionary.
id2word = dictionary.id2token

t0=time.time()

print('Nombre de sujets : {}'.format(num_topics))

for eta in range(1,10,2):
    eta = 0.1*eta +0.01
    for alpha in range(1,10,2):
        alpha = 0.1*alpha +0.01
        print('Hyperparrametres : ({0:.2f}, {1:.2f})'.format(alpha, eta))
        t1 = time.time()
        try:
            model = LdaMulticore(
                random_state=100,
                corpus = corpus,
                id2word = id2word,
                chunksize = chunksize,
                alpha = alpha,
                eta = eta,
                iterations = iterations,
                num_topics = num_topics,
                passes = passes,
                eval_every = eval_every
            )
            top_topics = model.top_topics(corpus)
            avg_topic_coherence = sum([t[1] for t in top_topics]) / num_topics
            print('Average topic coherence: %.4f.' % avg_topic_coherence)

            coherence_model_lda = CoherenceModel(
                model = model, 
                texts = corpora, 
                dictionary = dictionary,
                coherence = 'c_v'
            )
            coherence_lda = coherence_model_lda.get_coherence()
            print('Coherence Score: ', coherence_lda)

            model_results['Validation_Set'].append('No Title')
            model_results['Topics'].append(num_topics)
            model_results['Alpha'].append(alpha)
            model_results['Eta'].append(eta)
            model_results['Coherence'].append(coherence_lda)

            print('Processing Time : {} seconds'.format(time.time() - t1) )
            print('\n')

        except :
            print('Problem pour {} sujets '.format(num_topics))
            print('Processing Time : {} seconds'.format(time.time() - t1) )
            print('\n')
    
print('Over all Time : {} seconds'.format(time.time() - t0) )

Nombre de sujets : 50
Hyperparrametres : (0.11, 0.11)
Average topic coherence: -3.1256.
Coherence Score:  0.5414509701092045
Processing Time : 400.6065299510956 seconds


Hyperparrametres : (0.31, 0.11)
Average topic coherence: -3.4308.
Coherence Score:  0.5122584796162262
Processing Time : 429.3266005516052 seconds


Hyperparrametres : (0.51, 0.11)
Average topic coherence: -3.2424.
Coherence Score:  0.5388704326196987
Processing Time : 347.1789581775665 seconds


Hyperparrametres : (0.71, 0.11)
Average topic coherence: -3.2694.
Coherence Score:  0.5352727632371423
Processing Time : 305.8741512298584 seconds


Hyperparrametres : (0.91, 0.11)
Average topic coherence: -3.1687.
Coherence Score:  0.5306691589210092
Processing Time : 289.0265517234802 seconds


Hyperparrametres : (0.11, 0.31)
Average topic coherence: -3.2054.
Coherence Score:  0.5229831980939812
Processing Time : 370.0806214809418 seconds


Hyperparrametres : (0.31, 0.31)
Average topic coherence: -3.4287.
Coherence Score:  

Ici on converge vers un modèle.

In [252]:
# for doc in corpus:
bar = progress_bar(10, 'treatement', 1e-2)
num_topics = 50
columns = ["Topic{}".format(i) for i in range(0, num_topics, 1)]
docnames = ["Doc{}".format(0)]

doc_topic = pd.DataFrame(columns=columns)

bar.update_progress(0)
for i, doc in enumerate(corpus):
    progress = i/len(corpus)
    serie = pd.Series()
    for item in model.get_document_topics(doc):
    #     print(item)
        feat = 'Topic{0:.0f}'.format(item[0])
    #     print(type(item[1]))
        serie[feat] = item[1]
    doc_topic = doc_topic.append(serie, ignore_index = True)
    bar.update_progress(progress)

doc_topic

<ipython-input-252-2a6910c78ba5>:12: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  serie = pd.Series()


Progress treatement: [########################################] 99.00% 1:20:41.309158

Topic0    Topic1    Topic2    Topic3    Topic4    Topic5    Topic6  \
0           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1      0.010954  0.015573  0.010245  0.010284  0.010182  0.020608  0.011283   
2      0.017001  0.203264       NaN       NaN       NaN       NaN       NaN   
3      0.010447  0.010284  0.035680  0.206421  0.018857  0.010886  0.014202   
4           NaN       NaN       NaN  0.032625       NaN       NaN  0.016015   
...         ...       ...       ...       ...       ...       ...       ...   
77777       NaN       NaN  0.025260  0.027876       NaN       NaN       NaN   
77778  0.012325  0.013298  0.045271  0.012359  0.012731  0.013151  0.014949   
77779       NaN  0.029005  0.024273  0.014651       NaN       NaN  0.049698   
77780       NaN       NaN  0.042639  0.057942       NaN  0.010134  0.013357   
77781  0.047691       NaN       NaN       NaN       NaN  0.017311       NaN   

         Topic7    Topic8    Topic9   Topic10   Topic11   Topic12   Topic13  \
0      0.027869       NaN  0.014432       NaN  0.049295  0.016701  0.022718   
1      0.011744  0.019706  0.015804  0.010487  0.010148  0.010577       NaN   
2      0.010493       NaN       NaN       NaN       NaN       NaN       NaN   
3      0.010188  0.010485  0.010462  0.010657  0.026188  0.011768  0.010690   
4           NaN       NaN       NaN  0.012525  0.062390       NaN       NaN   
...         ...       ...       ...       ...       ...       ...       ...   
77777       NaN       NaN       NaN       NaN       NaN       NaN       NaN   
77778  0.013045  0.057804  0.012411  0.015527  0.013116  0.016265  0.013522   
77779  0.013491       NaN       NaN       NaN       NaN  0.073121       NaN   
77780  0.026056       NaN       NaN  0.048373       NaN  0.012958  0.035898   
77781       NaN       NaN  0.034060       NaN       NaN       NaN  0.024413   

        Topic14   Topic15   Topic16   Topic17   Topic18   Topic19   Topic20  \
0           NaN       NaN       NaN       NaN       NaN  0.041337       NaN   
1      0.011646  0.038098  0.010533       NaN       NaN  0.010179  0.015761   
2      0.039807       NaN       NaN  0.081560       NaN       NaN       NaN   
3      0.010226  0.011056  0.010387  0.010248  0.010305  0.010486  0.012354   
4           NaN       NaN       NaN       NaN       NaN  0.035826  0.238975   
...         ...       ...       ...       ...       ...       ...       ...   
77777       NaN       NaN  0.053346       NaN       NaN  0.324074       NaN   
77778  0.012973  0.012293  0.012684  0.188333  0.012109  0.012305  0.021895   
77779       NaN       NaN       NaN       NaN       NaN       NaN  0.015020   
77780       NaN       NaN       NaN  0.040458       NaN       NaN  0.076573   
77781  0.038598  0.086765       NaN       NaN       NaN       NaN       NaN   

        Topic21   Topic22   Topic23   Topic24   Topic25   Topic26   Topic27  \
0      0.019644       NaN  0.015863       NaN       NaN       NaN  0.172819   
1           NaN       NaN  0.010187  0.371881  0.010930  0.010094  0.010048   
2           NaN  0.011767  0.011837  0.233645       NaN       NaN  0.014212   
3      0.010859  0.010703  0.010762  0.010156  0.010949  0.010954  0.010351   
4      0.018092  0.010616       NaN       NaN  0.019194       NaN       NaN   
...         ...       ...       ...       ...       ...       ...       ...   
77777       NaN  0.018583       NaN       NaN       NaN       NaN       NaN   
77778  0.012217  0.012163  0.025032  0.013538  0.012730  0.012957  0.013430   
77779  0.018299       NaN       NaN       NaN       NaN       NaN       NaN   
77780       NaN       NaN  0.012097       NaN       NaN  0.013740  0.017514   
77781       NaN  0.174710       NaN       NaN       NaN       NaN       NaN   

        Topic28   Topic29   Topic30   Topic31   Topic32   Topic33   Topic34  \
0           NaN       NaN       NaN       NaN       NaN       NaN       NaN   
1           NaN  0.010048  0.022313  0.011734       NaN

In [205]:
def Doc2tags(row, words, bar=None, Lenght=None):
    if Lenght is not None:
        progress = row.name/Lenght
    serie = pd.Series()
    for tag in row['Tags']:
        if tag in words:
            serie[tag] = 1
    if bar is not None:
        bar.update_progress(progress)
    return serie

In [253]:
df = DataTagged.copy()
doc_tag = pd.DataFrame(columns=words)
bar = progress_bar(10, 'treatement', 1e-2)

doc_tag = pd.DataFrame(columns=words)

bar.set_progress(0)

doc_tag = doc_tag.append(
    df.apply(
        Doc2tags,
        args=(words,bar,len(df)),
        axis = 1
    )
)

doc_tag

Progress treatement: [#---------------------------------------] 2.00% 0:00:02.134317

<ipython-input-205-93c4f159465b>:4: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  serie = pd.Series()


Progress treatement: [#########################################] 102.00% 0:01:47.097740

In [255]:
doc_tag

python  javascript  c++   c#  java    c  php  html  reactjs  sql  \
0         0.0         0.0  0.0  0.0   0.0  0.0  0.0   0.0      0.0  0.0   
1         0.0         0.0  0.0  0.0   0.0  0.0  0.0   1.0      0.0  0.0   
2         0.0         0.0  0.0  0.0   0.0  0.0  0.0   1.0      0.0  0.0   
3         0.0         0.0  1.0  0.0   0.0  0.0  0.0   0.0      0.0  0.0   
4         0.0         0.0  0.0  0.0   0.0  1.0  0.0   0.0      0.0  0.0   
...       ...         ...  ...  ...   ...  ...  ...   ...      ...  ...   
79891     0.0         0.0  0.0  0.0   0.0  1.0  0.0   0.0      0.0  0.0   
79892     0.0         1.0  0.0  0.0   0.0  0.0  0.0   0.0      0.0  0.0   
79893     0.0         0.0  0.0  0.0   1.0  0.0  0.0   0.0      0.0  0.0   
79894     0.0         0.0  0.0  0.0   0.0  1.0  0.0   0.0      0.0  0.0   
79895     0.0         0.0  0.0  0.0   0.0  0.0  0.0   0.0      0.0  0.0   

       arrays  python-3.x  node.js  android  css  mysql  angular  laravel  \
0         0.0         0.0      0.0      0.0  0.0    0.0      0.0      0.0   
1         0.0         0.0      0.0      0.0  1.0    0.0      0.0      0.0   
2         0.0         0.0      0.0      0.0  1.0    0.0      0.0      0.0   
3         0.0         0.0      0.0      0.0  0.0    0.0      0.0      0.0   
4         0.0         0.0      0.0      0.0  0.0    0.0      0.0      0.0   
...       ...         ...      ...      ...  ...    ...      ...      ...   
79891     0.0         0.0      0.0      0.0  0.0    0.0      0.0      0.0   
79892     0.0         0.0      0.0      0.0  0.0    0.0      0.0      0.0   
79893     0.0         0.0      0.0      0.0  0.0    1.0      0.0      0.0   
79894     0.0         0.0      0.0      0.0  0.0    0.0      0.0      0.0   
79895     0.0         0.0      0.0      0.0  0.0    0.0      0.0      0.0   

       json    r  sql-server  jquery  swift  pandas  typescript  excel  vba  \
0       0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
1       0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
2       0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
3       0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
4       0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
...     ...  ...         ...     ...    ...     ...         ...    ...  ...   
79891   0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
79892   0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
79893   0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
79894   0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   
79895   0.0  0.0         0.0     0.0    0.0     0.0         0.0    0.0  0.0   

       ios  regex  algorithm  string  bash  flutter  .net  django  linux  \
0      0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
1      0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
2      0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
3      0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
4      0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
...    ...    ...        ...     ...   ...      ...   ...     ...    ...   
79891  0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
79892  0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
79893  0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
79894  0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   
79895  0.0    0.0        0.0     0.0   0.0      0.0   0.0     0.0    0.0   

       asp.net-core  docker  list  spring-boot  vue.js  amazon-web-services  \
0               0.0     0.0   0.0          0.0     0.0                  0.0   
1               0.0     0.0   0.0          0.0     0.0                  0.0   
2               0.0     0.0   0.0          0.0     0.0                  0.0   
3  

In [254]:
# np.asmatrix(doc_topic.values)
doc_topic = doc_topic.fillna(0)
# np.asmatrix(doc_tag.values)
doc_tag = doc_tag.fillna(0)

Tag_topic = pd.DataFrame(np.dot(doc_topic.T,doc_tag), columns = doc_tag.columns, index = doc_topic.columns)
Tag_topic

python  javascript          c++          c#        java  \
Topic0     95.272437  108.758096    68.872931   64.851239   41.059548   
Topic1    164.881595  390.808274    60.554267  115.882416   59.052700   
Topic2    206.805507  330.698167   192.605748  106.500028   74.814523   
Topic3    114.349691   59.073189  1014.077650  125.938147  104.298628   
Topic4    402.672726   76.388487    71.296941   68.008944   48.583619   
...              ...         ...          ...         ...         ...   
Topic355    0.000000    0.000000     0.000000    0.000000    0.000000   
Topic356    0.000000    0.000000     0.000000    0.000000    0.000000   
Topic357    0.000000    0.000000     0.000000    0.000000    0.000000   
Topic358    0.000000    0.000000     0.000000    0.000000    0.000000   
Topic359    0.000000    0.000000     0.000000    0.000000    0.000000   

                   c         php        html    reactjs        sql  \
Topic0     37.704489   24.927681   25.897529  28.950690  16.968955   
Topic1     34.736140  221.414807  243.486064  75.135827  30.605875   
Topic2    113.884279   87.671365   56.108689  68.800651  33.097678   
Topic3    306.997845   19.729582   14.699148  14.166947  23.055411   
Topic4     35.172344   31.144702   23.226114  19.758469  21.295605   
...              ...         ...         ...        ...        ...   
Topic355    0.000000    0.000000    0.000000   0.000000   0.000000   
Topic356    0.000000    0.000000    0.000000   0.000000   0.000000   
Topic357    0.000000    0.000000    0.000000   0.000000   0.000000   
Topic358    0.000000    0.000000    0.000000   0.000000   0.000000   
Topic359    0.000000    0.000000    0.000000   0.000000   0.000000   

              arrays  python-3.x    node.js    android        css      mysql  \
Topic0     35.436735   20.311741  17.328775  14.164940  16.044481   9.942679   
Topic1     35.448081   33.152814  36.865232  18.671228  71.158458  45.435635   
Topic2     58.512703   46.488809  64.035204  23.635619  20.093286  26.486208   
Topic3    103.557190   25.706905  11.241393  22.452030   9.586901  15.801798   
Topic4     28.197264   60.749128  16.375202  15.247570  12.276215  14.931515   
...              ...         ...        ...        ...        ...        ...   
Topic355    0.000000    0.000000   0.000000   0.000000   0.000000   0.000000   
Topic356    0.000000    0.000000   0.000000   0.000000   0.000000   0.000000   
Topic357    0.000000    0.000000   0.000000   0.000000   0.000000   0.000000   
Topic358    0.000000    0.000000   0.000000   0.000000   0.000000   0.000000   
Topic359    0.000000    0.000000   0.000000   0.000000   0.000000   0.000000   

            angular    laravel       json          r  sql-server      jquery  \
Topic0    17.748350  13.844523  21.363956   9.994491   10.207549    9.926984   
Topic1    62.237771  69.241590  34.045988  14.235934   12.535176  152.303190   
Topic2    24.491478  42.627767  26.724217  31.360320   18.429188   51.115686   
Topic3    10.643263   7.855854  15.127692  11.962274   15.755028    5.192719   
Topic4    12.016308  21.221090  15.121104  34.390413   11.939000   10.041093   
...             ...        ...        ...        ...         ...         ...   
Topic355   0.000000   0.000000   0.000000   0.000000    0.000000    0.000000   
Topic356   0.000000   0.000000   0.000000   0.000000    0.000000    0.000000   
Topic357   0.000000   0.000000   0.000000   0.000000    0.000000    0.000000   
Topic358   0.000000   0.000000   0.000000   0.000000    0.000000    0.000000   
Topic359   0.000000   0.000000   0.000000   0.000000    0.000000    0.000000   

               swift     pandas  typescript      excel        vba         ios  \
Topic0    271.911961   9.071804   15.853654   6.915982   5.739724  189.690473   
Topic1     14.194954  10.958807   31.184848  14.233533  14.156927   11.134812   
Topic2     20.978725  19.521219   39.477413  18.183867  16.512763   13.569564   
Topic3     21.988850  12.218257   10.601949   7.76

In [298]:
values = []
words = []

for topic, obj in enumerate(top_topics):
    print('topics : ', topic)
    for truc in obj:
        if type(truc) is list:
            for item in truc:
                values.append(item[0])
                words.append(item[1])
            print('Words : ', words)
        else :
            print('Coherence : ', truc)
            
        values = []
        words = []

topics :  0
Words :  ['div', 'class', 'button', 'style', 'px', 'cs', 'html', 'display', 'color', 'text', 'span', 'card', 'href', 'background', 'width', 'body', 'border', 'click', 'li', 'container']
Coherence :  -2.0822865600815423
topics :  1
Words :  ['form', 'page', 'input', 'post', 'html', 'td', 'search', 'id', 'th', 'tr', 'class', 'control', 'submit', 'button', 'ajax', 'text', 'php', 'jquery', 'title', 'placeholder']
Coherence :  -2.2329279101234594
topics :  2
Words :  ['http', 'request', 'response', 'api', 'com', 'header', 'content', 'url', 'status', 'get', 'application', 'post', 'access', 'body', 'curl', 'error', 'browser', 'fetch', 'cache', 'localhost']
Coherence :  -2.2569806230510085
topics :  3
Words :  ['state', 'event', 'component', 'import', 'const', 'react', 'default', 'export', 'action', 'return', 'prop', 'store', 'classname', 'render', 'constructor', 'payload', 'hook', 'router', 'app', 'setstate']
Coherence :  -2.393313481900229
topics :  4
Words :  ['file', 'line', 'p

#### Scikit-learn library

In [21]:
class MyLDAWithPerplexityScorer(skl.decomposition.LatentDirichletAllocation):

    def score(self, X, y=None):

        # You can change the options passed to perplexity here
        score = super(MyLDAWithPerplexityScorer, self).perplexity(X, sub_sampling=False)

        # Since perplexity is lower for better, so we do negative
        return -1*score

In [111]:
max_iter = 10
no_top_words = 10

search_params = {
    'n_components': range(1,10),
    'learning_decay': [.5, .7, .9]
}

# data_classique = data_classique.select_dtypes(exclude=['datetime64'])
Values = DataBow.values
features_names = DataBow.columns

lda = MyLDAWithPerplexityScorer(
#     n_components = n_topics,
    max_iter = max_iter, 
    learning_method = 'online',
    learning_offset = 50,
#     learning_decay = 0.7,
    random_state = 0,
    verbose = 0
)

model = GridSearchCV(
    n_jobs = -1,
    cv = None,
    error_score = 'raise',
    estimator = lda,
    param_grid = search_params,
    scoring = None,
    verbose = 2
)

model.fit(Values)

print('\n')
for topic_idx, topic in enumerate(model.best_estimator_.components_):
    print('Topic %d:' % (topic_idx))
    print(' '.join([features_names[i] for i in topic.argsort()[:-no_top_words - 1:-1]]))

print('\n')
# Log Likelyhood: Higher the better
print("Log Likelihood: ", model.best_estimator_.score(Values))

# Perplexity: Lower the better. Perplexity = exp(-1. * log-likelihood per word)
print("Perplexity: ", model.best_estimator_.perplexity(Values))


# See model parameters
print(model.best_estimator_.get_params())

Fitting 5 folds for each of 27 candidates, totalling 135 fits


Topic 0:
error file data class python name value code app import


Log Likelihood:  -5108.607174291086
Perplexity:  5108.607174291086
{'batch_size': 128, 'doc_topic_prior': None, 'evaluate_every': -1, 'learning_decay': 0.9, 'learning_method': 'online', 'learning_offset': 50, 'max_doc_update_iter': 100, 'max_iter': 10, 'mean_change_tol': 0.001, 'n_components': 1, 'n_jobs': None, 'perp_tol': 0.1, 'random_state': 0, 'topic_word_prior': None, 'total_samples': 1000000.0, 'verbose': 0}


In [157]:
model.cv_results_
params = model.cv_results_['params']
scores_mean = model.cv_results_['mean_test_score']
grid_param_1 = []
name_param_1 = 'N_components'
grid_param_2 = []
name_param_2 = 'Learning_decay'

for i, row in enumerate(params):
    grid_param_1.append(row['n_components'])
    grid_param_2.append(row['learning_decay'])

dfpar = pd.DataFrame({
    'Param1' : grid_param_1,
    'Param2' : grid_param_2,
    'Mean_score' : scores_mean
})
u_par2 = dfpar['Param2'].unique()
# # Plot Grid search scores
_, ax = plt.subplots(1,1)

# # Param1 is the X-axis, Param 2 is represented as a different curve (color line)
for idx, val in enumerate(u_par2):
    df2 = dfpar[dfpar['Param2'] == val]
    ax.plot(dfpar['Param1'], dfpar['Mean_score'], '-o', label= name_param_2 + ': ' + str(val))

ax.set_title("Grid Search Scores", fontsize=20, fontweight='bold')
ax.set_xlabel(name_param_1, fontsize=16)
ax.set_ylabel('CV Average Score', fontsize=16)
ax.legend(loc="best", fontsize=15)
ax.grid('on')

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

### 4.B) Negative Matrix Factorisation (NMF)

## 5) Modèle supervisé

### 5.A) One versus Rest

In [ ]:
# logistic regression for multi-class classification using a one-vs-rest

# define dataset
X, y = make_classification(
    n_samples=1000,
    n_features=10,
    n_informative=5,
    n_redundant=5,
    n_classes=3,
    random_state=1
)

# define model
model = LogisticRegression()
# define the ovr strategy
ovr = OneVsRestClassifier(model)
# fit model
ovr.fit(X, y)
# make predictions
yhat = ovr.predict(X)

### 5.B) One versus One

### 5.C) Chain